### ISSUE TITLE
Clarify the debugging options for the Former2 CLI

### ISSUE THREAD

**Issue by jlandowner** [iann0036/former2#101]
Hi, I like the Former2 CLI and would like to contribute to the improvement. (Thank you for merging some PRs!)

I have an opinion about its debug flags.
It's hard for new users to understand the difference between the `--output-debug` flag and the `--debug` flag.
I think the `--debug` flag is more general and only this flag is easier to understand the options.

Now I have a question about the purpose of the `--output-debug` debug file.
And is it ok to output the debug file just with `--debug` flag and remove `--output-debug` flag? 

Thank you.

**Comment by iann0036** [comment]
Hey @jlandowner,

Appreciate your help!

On the debug flags, `--output-debug` is for outputting the raw SDK call responses the way it is mapped internally, which can be helpful when a specific mapping to another output (like CloudFormation) fails, or when adding new properties.

`--debug` is purely for solving problems, as per your understanding.

They do fairly different functions and are essentially debugging at different layers (application outputs vs. the core application itself). To match the former2.com site, happy to change `--output-debug` to `--output-raw-debug` if that makes better sense, or adjust the README / `--help` options to make better sense.

**Comment by jlandowner** [comment]
Thank you for the details. I understood.
 
I didn't know that the fomer2.com site outputs `Raw Output (Debug)` as an output option.
But still I think the word `debug` make it confusing in the context of CLI option.
How about removing the word 'debug' like `--output-raw-data` or `--output-raw-mapping-data`, and mentioning it is for debug in help description?

**Comment by iann0036** [comment]
Makes sense to me. `--output-raw-data` it is.

**Comment by jlandowner** [comment]
Thank you for your update!
