### ISSUE TITLE
Integration with AWS SSO

### ISSUE THREAD

**Issue by balakotaru** [iann0036/former2#109]
Hello,

Is there any possibility to integrate fromer2.com with AWS sso single-sign-on, i hosted it on locally, if possible give me the metadata file to create Custom SAML 2.0 Applications to integrate with AWS sso.

Thanks
Balaswamy

**Comment by iann0036** [comment]
Hey @balakotaru,

I don't have anything for that right now. I believe that may require some server-side processing (something deliberately not present in the architecture), but I'll look into it.

**Comment by balakotaru** [comment]
Hi thanks for the response.
