### ISSUE TITLE
Rate Exceeded on AWS API

### ISSUE THREAD

**Issue by bbuivn** [iann0036/former2#11]
Hi,

I am currently having issues with the rate limit on AWS side due to a high number of resources on my account.
I  am running the container locally but I do have the same issue with the version hosted on `https://former2.com`.

```
Env:
macOS 10.14.4
Docker version 18.09.2, build 6247962
Image build on former2 commit 5d8ea581530dda7272e391ded3eaa7c00f6cbe53
Firefox 66.0.5 with former2 extension installed
```

The issue happens when launching the scan.
eg. of requests
```
url: https://ecs.eu-west-1.amazonaws.com/
{"taskDefinition":"arn:aws:ecs:eu-west-1:<accountid>:task-definition/<taskdefinition>:<version>"}
```
This ends up with the following error:
```
HTTP/1.1 400 Bad Request
x-amzn-RequestId: 6af5fd30-765e-11e9-a5f9-b7e8a953a005
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Content-Type: application/x-amz-json-1.1
Content-Length: 58
Date: Tue, 14 May 2019 15:39:10 GMT
Connection: close

{"__type":"ThrottlingException","message":"Rate exceeded"}
```

Could we add either a mecanism to retry on rate limited error or a rate limit setting in the configuration?

Thanks!

**Comment by iann0036** [comment]
Hi Benoit,

Added some conditions to backoff in this situation (https://github.com/iann0036/former2/commit/67843a34f98b2046d5bd72ec8e52422de66f63b3).

Could you pull the latest and try it out? Or use the hosted version.

**Comment by bbuivn** [comment]
Hi Ian,

It works perfectly! (I've rebuilt the image)
Thanks a lot!
