### ISSUE TITLE
Step function and S3 - slow/not loading

### ISSUE THREAD

**Issue by sree-kanth** [iann0036/former2#110]
Hi Ian, I have hosted former2 on a local server and used it to generate templates for several AWS services including Lambda, Glue and so on. When I try to get to Step functions and S3, I haven't had much success loading those resources and generating the templates for them. I've provided ReadOnlyAccess to these services like for all others. Have you observed this in the past? Do you know if it'd work faster if I used the web-based version?

**Comment by iann0036** [comment]
Hey @sree-kanth,

It should make zero difference between local server and the web-based version. Do you happen to have a lot of resources for S3 / Step Functions? If possible, could you check the web console logs to see if you have any indications of backed-off calls?

**Comment by sree-kanth** [comment]
Thanks for the swift revert, Ian. Btw, forgot to appreciate you for this wonderful tool that you've created - thank you so very much!

There's less than 10 buckets in S3, and less than 25 GB data in all of them put together. There are only 2 Step functions, with about 25 steps in the StateMachine. I am a bit of a newbie to web server - how do I check web console logs? 

Thanks again!

**Comment by iann0036** [comment]
Unusual 🤔 

If you're in Chrome, it's under View -> Developer -> Developer Tools (Console tab).

If you're in Firefox, it's Tools -> Web Developer -> Web Console.

Feel free to paste anything that might be relevant, but be sure to strip out any account information or identifying strings.

**Comment by sree-kanth** [comment]
Thanks! It looks like a CORS issue:

index.html#section-storage-s3:1 Access to XMLHttpRequest at 'https://s3.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
s3.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

index.html#section-storage-s3:1 Access to XMLHttpRequest at 'https://s3.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
s3.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

index.html#section-storage-s3:1 Access to XMLHttpRequest at 'https://s3.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
s3.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

index.html#section-storage-s3:1 Access to XMLHttpRequest at 'https://s3.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
mappings.js:2 Skipping S3.listBuckets NetworkingError
s3.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

s3.js:280 Uncaught (in promise) null
(index):1 Not allowed to load local resource: file:///lib/drawio/src/main/webapp/index.html?embed=1&libraries=1&proto=json&local=1&sync=none&browser=0&gapi=0&db=0&od=0&tr=0&gh=0&gl=0&stealth=1&math=0&picker=0&libs=aws4&spin=1&p=page&saveAndExit=0&noSaveBtn=1&noExitBtn=1
index.html#section-applicationintegration-stepfunctions:1 Access to XMLHttpRequest at 'https://states.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
states.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

index.html#section-applicationintegration-stepfunctions:1 Access to XMLHttpRequest at 'https://states.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
states.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

index.html#section-applicationintegration-stepfunctions:1 Access to XMLHttpRequest at 'https://states.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
states.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

index.html#section-applicationintegration-stepfunctions:1 Access to XMLHttpRequest at 'https://states.eu-central-1.amazonaws.com/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
mappings.js:2 Skipping StepFunctions.listStateMachines NetworkingError
states.eu-central-1.amazonaws.com/:1 Failed to load resource: net::ERR_FAILED

stepfunctions.js:150 Uncaught (in promise) null

I have installed the Chrome extension. Do I need to configure it in any particular way for it to be effective?

**Comment by iann0036** [comment]
Ah, I should have caught that. If you're hosting your own version somewhere other than localhost:80, you'll need to tweak the extension manually. Instructions on that [here](https://github.com/iann0036/former2/blob/master/HOSTING.md).

**Comment by sree-kanth** [comment]
Ah, thanks Ian - will follow those instructions on that page you've mentioned then.

Cheers,
Sree.

**Comment by sree-kanth** [comment]
I tried this and it worked for S3! Am able to access S3 resources now.

For Step Functions, however, the Statemachine doesn't show up straightaway. When I hit "Refresh" inside the Application Integration -> Step Function console, the Statemachines get listed for a brief second/flashes and vanish as soon as the page is refreshed. This seemed very strange. Couldn't find anything in the console logs either.

**Comment by iann0036** [comment]
Cheers @sree-kanth,

That second one was indeed a bug! See the linked commit for the fix.

**Comment by sree-kanth** [comment]
You're a champion! Thanks for fixing this, Ian - works perfectly now.

**Comment by sree-kanth** [comment]
On a similar note, I don't see Glue Classifiers getting listed either. Could this also be a javascript bug?

**Comment by iann0036** [comment]
I don't spot anything obviously wrong with them. Notably, there's a check to say that it must be a Grok, XML or JSON classifier and it must have a name.

Can you see a reference to it in the Raw Output (Debug) section?

**Comment by sree-kanth** [comment]
Ah, that's probably it! Mine is a CSV classifier (which is the other type permitted by Glue - https://docs.aws.amazon.com/glue/latest/dg/custom-classifier.html) and hence is not recognised. Would it be possible to include this as well, please? Thanks!

**Comment by iann0036** [comment]
Cheers for that. Added in as requested.

**Comment by sree-kanth** [comment]
Perfect, works now Ian. Thanks much!
