### ISSUE TITLE
While scanning the account getting the error

### ISSUE THREAD

**Issue by balakotaru** [iann0036/former2#112]
Hi Iann,

I am getting below errors while scanning the accounts (i hosted it on locally)
with Administrator access getting 1st error only (SSO)
1. **Error calling Inspector.describeResourceGroups** 
Minimum size of resourceGroupArns is 1, size of the given list is O 

with Readonly access i am getting both 1 and 2 errors

2. **Error calling ServiceCatalog.describeProductAsAdmin** 
There are no local or default products with id prodview-xxxx
 
Former2 plugin was not installed, if i installed plugin it is giving another error update plugin.
Can you please help on this.

Thanks
Balaswamy

**Comment by iann0036** [comment]
Hi @balakotaru,

Thanks for reaching out. I've added a couple of fixes for those issues you mentioned.

The second may actually be a permissions issue with the ReadOnlyAccess policy provided by AWS, so I'll chase them for clarification. Additionally, it's advised to always have the plugin installed to avoid CORS issues.
