### ISSUE TITLE
Scanning getting stuck

### ISSUE THREAD

**Issue by andrea-82** [iann0036/former2#113]
Hi,

When I press the "scanning" button it gets stuck at some point with no clear indication of what might be going wrong.
Sometimes it gets stuck saying "Scanning... (39/111)" and some other times "Scanning... (45/111)".

Is there a way to make the scanning more verbose maybe?

Thanks,
Andrea

**Comment by iann0036** [comment]
Hi @andrea-82,

Thanks for reaching out. Is there anything that is shown in your Web Console? (View -> Developer -> JavaScript Console in Chrome)

Can you also clarify whether the "Former2 Helper" browser extension is installed?

**Comment by andrea-82** [comment]
No. Thank you for the amazing tool!

I was on Firefox and yes, the extension was installed.

After your message, I tested the same in Chrome (installing the extension) and the scan worked immediately.
I consider my personal issue solved but I'm happy to provide more details about the Firefox issue if you like:

Here is the screenshot of what I'm getting in Firefox
![former2HelperErrorInFirefox](https://user-images.githubusercontent.com/922382/94986303-895f1100-0555-11eb-92de-61182649d693.png)

**Comment by iann0036** [comment]
Hi @andrea-82,

Thanks soo much for that detail!

I believe I found the underlying issue for Firefox. If you have time, I'd appreciate it if you could test if that fixes your problem.

**Comment by andrea-82** [comment]
Hi @iann0036 - I can confirm this is now fixed in firefox too!
Great stuff!

Thanks,
Andrea
