### ISSUE TITLE
Problem With Scan Process

### ISSUE THREAD

**Issue by jnarvaezp** [iann0036/former2#116]
Hello, 

I am currently trying to use former2 to bring up a sage maker display, but when I run the scan option the following image appears.

![image](https://user-images.githubusercontent.com/788597/95281283-61550380-081c-11eb-9343-5749eead4044.png)

I have deleted and reinstalled the plugin.

Maybe someone else has done the same?

Thanks for the help.

**Comment by iann0036** [comment]
Hey @jnarvaezp,

Thanks for picking up on that! I've pushed a fix that should hopefully remove the error you're seeing.

Let me know how that goes.

**Comment by jnarvaezp** [comment]
Hi @iann0036 

Thanks, it works properly
