### ISSUE TITLE
Scan Missed ElastiCache Memcached Clusters

### ISSUE THREAD

**Issue by smartinec** [iann0036/former2#118]
The former2 scan feature did not pick up my 2 ElastiCache Memcached clusters. Everything else seemed to work. Here are the results:

![aws_memcached_clusters](https://user-images.githubusercontent.com/1090227/95863922-bfa94700-0d32-11eb-8330-8b39ac5ad5d2.png)

![former2_elasticache_clusters](https://user-images.githubusercontent.com/1090227/95863936-c33cce00-0d32-11eb-974b-be3c872eb276.png)

**Comment by iann0036** [comment]
Hey @smartinec,

Thanks for letting me know! That bug should be fixed now, feel free to re-attempt.

**Comment by smartinec** [comment]
Works now. Thanks for the quick turnaround.
