### ISSUE TITLE
Issue on Cognito section

### ISSUE THREAD

**Issue by Zivaga** [iann0036/former2#12]
When clicking on Cognito section, there is an error in the console:
`datatables.js:23983 Uncaught (in promise) TypeError: data.Roles.join is not a function
    at datatables.js:23983
    at async Promise.all (/index 0)
    at async Promise.all (/index 0)
    at /async http:/127.0.0.1/js/datatables.js:23972`

And then, whatever the sub-level (user pool, user client...), nothing happens anymore.

**Comment by iann0036** [comment]
Hey @Zivaga,

Thanks heaps for picking up on that! A fix should be in now, let me know if it works for you.

**Comment by Zivaga** [comment]
Hello

Yep, it works now.

Thanks a lot for your reactivity!

**Comment by pilipicus** [comment]
Everything was perfectly working last August that I used Former2 but today I'm getting a few different "CognitoServiceIdentityProvider " errors, without being able to get any element from the scanning.
I reinstalled the webApp and the Chrome browser extension, doing all the changes in the file following the guide (https://github.com/iann0036/former2/blob/master/HOSTING.md
), but I'm getting the same errors.
