### ISSUE TITLE
Former2 is not picking up any VPC resource ( subnets/cidr/route tables etc )

### ISSUE THREAD

**Issue by arunsubbu-github** [iann0036/former2#121]
Former2 is not picking up any VPC resource ( subnets/cidr/route tables etc )

**Comment by iann0036** [comment]
Hi @arunsubbu-github,

I can't seem to replicate your issue, do you have more detail?

One notable recent change is that the default VPC will no longer be populated in the table, as they are considered a resource that should not be codified.

**Comment by arunsubbu-github** [comment]
Hello Iann0036

Thanks for the quick response - looks like that's the issue I encountered.   Is it possible to get the previous version of Former2 that has this capability?

**Comment by iann0036** [comment]
Apologies, I wasn't aware that was something required.

I'll add a setting toggle in a day or two to allow for those resources to be present (it'll be off by default however).

**Comment by arunsubbu-github** [comment]
That's fantastic news - this switch will help us generate a full picture of our infrastructure, whenever we need it.

Thanks for your help. It will be great if you can add a note on how to enable this switch when its ready.

**Comment by arunsubbu-github** [comment]
By the way, great tool and easy to use.  Love it.

**Comment by iann0036** [comment]
Hey @arunsubbu-github,

Just noting that the option to include default resources is now available. You can enable this within the UI by going to **Setup > Settings** and clicking the **Include Default Resources** option. This option will be remembered by your browser in subsequent visits to the site.

If you're using the CLI, the option `--include-default-resources` will have the same effect.

Let me know how that goes.

**Comment by arunsubbu-github** [comment]
Thanks iann0036, it works like a charm.  Really appreciate your timely help

**Comment by iann0036** [comment]
Hey @altaurog,

_New_ VPC's created should indeed be codified, however AWS accounts come with [default VPCs](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html) which were never created by a person. So this option differentiates for when you use the default VPC and want to replicate the same elsewhere, or when you're auditing your infrastructure for changes humans made (so excludes default resources).

Hope that helps!

**Comment by altaurog** [comment]
Ah, got it, that makes sense.  Thank you so much for the clarification, @iann0036!
I guess if I have ‘legacy’ resources in the default VPC and I want to create a template that will allow me to import those resources into a new stack and then reproduce those resources elsewhere in non-default VPC, I will in any case have to leave VPC etc as template parameters and manage them some other way.
