### ISSUE TITLE
Terraform output does not contain SageMake endpoints

### ISSUE THREAD

**Issue by twitu** [iann0036/former2#122]
I'm scanning my account for SageMaker endpoints, endpoints config and models. All these are generated as part of Cloudformation output but not in Terraform output. I checked that terraform [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_endpoint) and it does have support for sagemaker resources.

I'm using this version 3ef327d6. Could this be something related to plugins or terraform version?

**Comment by iann0036** [comment]
Hey @twitu,

This is just me not up to date on some of the latest resources. [Here](https://github.com/iann0036/former2/blob/master/RESOURCE_COVERAGE.md#terraform-coverage) is the list of resources I've managed to map through, notably `aws_sagemaker_endpoint` and `aws_sagemaker_endpoint_configuration` isn't ready yet.

I'll prioritise those two for you, so I should have something for you in a week or so.

**Comment by iann0036** [comment]
Hi @twitu,

Thanks for your patience! Those SageMaker resources are now correctly mapped for Terraform outputs.

Let me know if you have any issues.

**Comment by twitu** [comment]
Hmm weird I'm using 90b1e379, but it's still not generating SageMaker for terraform. I'm using the UI is there anyway I can check the logs?

**Comment by iann0036** [comment]
Hey @twitu,

You can probably check if there's any web console logs (_View -> Developer -> JavaScript Console_ in Chrome).

Could you also check if the _Raw Output (Debug)_ section contains a reference to the resource. If it does, it'll simply be a mapping error.

**Comment by twitu** [comment]
It works!! 🥳 I don't know why it didn't work earlier. Thanks a lot for the super quick response.
