### ISSUE TITLE
Error calling MediaLive.describeCluster

### ISSUE THREAD

**Issue by Billy441** [iann0036/former2#127]
Hello I got this error when I tried to use the MediaLive Channels.

Error calling MediaLive.describeCluster
"The call to the SDK failed. You may need to update the Former2 Helper extension."

inputs and outputs working perfectly well. Only the channel instances are giving me this error.

**Comment by iann0036** [comment]
Hey @Billy441,

Thanks for raising! Looks like I was very distracted when writing that one 😲.

I've pushed an update that hopefully fixes that issue.

**Comment by velartur** [comment]
Yes, thank you so much @iann0036 it works now 👍
