### ISSUE TITLE
MediaPackage Output Generation error.

### ISSUE THREAD

**Issue by velartur** [iann0036/former2#128]
Hello @iann0036 now I'm getting this error when I try to generate the CDK output of MediaPackage 

Error
TypeError: obj.data.Tags.forEach is not a function

Thanks in advance ;)

**Comment by iann0036** [comment]
Hey @velartur,

Thanks for picking up on that. Pushed a fix that should hopefully help. Note there may be a cache of up to 5 minutes.

**Comment by velartur** [comment]
Helo @iann0036 Thank you so much for the answer, I tried several times but is still not generating any MediaPackage channel or endpoint and getting the same error. 
" TypeError: obj.data.Tags.keys is not a function"


Thanks in advance

**Comment by iann0036** [comment]
Hey @velartur,

Thanks for the confirmation. Could you try again now to see if the latest update fixes your issue?

**Comment by velartur** [comment]
Yes now is working. Thank you so much. 

Appreciate it
