### ISSUE TITLE
Greyed-out load of Eventbridge resources

### ISSUE THREAD

**Issue by sree-kanth** [iann0036/former2#129]
Hi Ian, 

I see that Eventbridge resources, although I see all of them, appear greyed-out with the loading cursor rotating, and I am not able to select/add them to generate the yaml definition. This is with my local server install on my Mac. Would be great if you could have a look. Thanks!

Sreekanth.

**Comment by iann0036** [comment]
Hey Sreekanth,

Thanks for raising!

Usually the greyed out section with resources underneath means either there was a general problem on the page, or a specific problem with another resource type in the same section (e.g. Event Buses or Schemas in this case).

Could you check your console for any errors when the grey screen is showing by going to View -> Developer -> JavaScript Console (assuming you're using Chrome) and let me know any errors that might be appearing in red.

**Comment by sree-kanth** [comment]
Thanks Ian!

Yes, that's what it looks like. Here's the error:

```
Uncaught (in promise) SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at eventbridge.js:359
    at async Promise.all (index 0)
    at async http:/127.0.0.1:8000/js/services/eventbridge.js:344
    at async updateDatatableApplicationIntegrationEventBridge (eventbridge.js:338)
```
Hope this helps.

**Comment by iann0036** [comment]
Hey Sreekanth,

That error certainly helped. It looks like I was making the assumption that your custom event bus had a policy attached, where it actually didn't.

I've pushed a fix for that so hopefully you won't see that issue again. Let me know how you go.

**Comment by sree-kanth** [comment]
Awesome - yes, fixed now Ian 👍 :)

Thanks much again mate!
