### ISSUE TITLE
Diagram output missing?

### ISSUE THREAD

**Issue by gvasquez95** [iann0036/former2#138]
I'm missing the "Diagram" output that was so useful and, just today I had to deliver a new one to one of our customers from their existing resources. Did you actually hide it?

**Comment by iann0036** [comment]
Hey @gvasquez95,

Thanks for reaching out. I wasn't aware this was a sought after feature. I've reinstated it now.

**Comment by gvasquez95** [comment]
Thanks a lot, it's a very useful feature!
