### ISSUE TITLE
"TypeError: Cannot read property 'Granularity' of undefined" when adding AutoScalingGroup

### ISSUE THREAD

**Issue by sc-pulsion** [iann0036/former2#14]
Adding an ASG in the London region but getting the above error. Other resources add correctly. Using https://former2.com. Do you have any idea why this is happening? Thanks.

**Comment by iann0036** [comment]
Hi there,

Thanks for reporting! Looks like an API call response wasn't handled correctly. Could you try again now? (note it may be cached for up to 5 minutes)

**Comment by sc-pulsion** [comment]
Thanks for getting back so quickly! I tested again in Chrome now and have the same issue, however have tested in a Firefox private windows and can get pull the correct info. I expect if I closed Chrome or cleared its cache it would work but cant test right now. Thanks again.

**Comment by iann0036** [comment]
Thanks for confirming. Feel free to reopen if the Chrome issue persists.
