### ISSUE TITLE
Docker build error when building for local hosting

### ISSUE THREAD

**Issue by iainelder** [iann0036/former2#143]
The DOCKERFILE includes instructions to build and run locally.

https://github.com/iann0036/former2/blob/a4edbc730eff94ac93e7d6fd034f318b8f6100e0/DOCKERFILE#L1-L2

When I execute the build command, I get the following error:

```text
$ docker build -t former2_local:1.0 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/isme/tmp/former2/Dockerfile: no such file or directory
```

It works if I use the `-f` option:

```text
$ docker build -f DOCKERFILE -t former2_local:1.0 .
Sending build context to Docker daemon  211.1MB
[...]
```

Note that Docker by default expects the file name to be spelled in title case: "Dockerfile".

I suppose spelling it in uppercase works on operating systems with case-insensitive file systems like macOS and Windows.

I use Ubuntu which has a case-sensitive file system and it's a bit more pedantic :-)

If there's no other reason to keep the current spelling, can we change it to what Docker expects?

**Comment by iann0036** [comment]
Apologies for the delay on this one - must've got lost in my inbox.

The Dockerfile has been renamed now - thanks for raising!

**Comment by iainelder** [comment]
Thanks!

I'll just reference these two commits here that complete the fix:

Removing the DOCKERFILE: https://github.com/iann0036/former2/commit/f5f9e52ef689d75dccae2f5c7615913d41a4bb35

Adding the Dockerfile: https://github.com/iann0036/former2/commit/6a13f385273de70158fc266741a3f41b113e1aeb

I'm guessing macOS's case insensitivity made that necessary :-D

**Comment by iann0036** [comment]
You would be correct :P
