### ISSUE TITLE
Former2 Helper SDK Failure

### ISSUE THREAD

**Issue by HSVAdam** [iann0036/former2#144]
Having issues with Edge & Firefox extension connection from former2 website.  Getting below errors:
`Error calling ECRPUBLIC.describeRepositories
"The call to the SDK failed. You may need to update the Former2 Helper extension."`
I have tried clearing cache and Firefox is a fresh install.

**Comment by iann0036** [comment]
Hey @HSVAdam,

Thanks for raising this. It looks like I neglected to update the helper in the recent release. This has been amended now and version 1.35 should be updated on your browser shortly (or you can manually update).

Let me know if you still experience issues after the update.

**Comment by HSVAdam** [comment]
I am not longer receiving the error popups when running a scan however the functionality does not appear to be working.  For instance I do not see my RDS instances.

**Comment by iann0036** [comment]
Hi @HSVAdam,

Thanks for reporting that. Looks like you might've helped catch a bug. I was erroneously filtering non-Aurora DB instances in the scan.

Could you retry your search for RDS instances?

**Comment by HSVAdam** [comment]
That looks like it did it.  Thank you very much @iann0036   Excellent tool by the way!

**Comment by iann0036** [comment]
Appreciate the help!

**Comment by ben-haverly-cfa** [comment]
I am receiving the same "The call to the SDK failed. You may need to update the Former2 Helper extension." error currently in Firefox. When I try in Chrome it instead says ""No response from extension".
