### ISSUE TITLE
Former2 and AWS Console Recorder Demonstrations

### ISSUE THREAD

**Issue by blake-enyart** [iann0036/former2#147]
Hi @iann0036!

I wasn't quite sure on the best way to present this, but I created some demonstration videos of Former2 and the AWS Console Recorder in action and thought they might be helpful to share out with you. Hope they are helpful!

* https://www.youtube.com/watch?v=u1crm24vTpA
* https://www.youtube.com/watch?v=APtTR-L4U7Q

**Comment by iann0036** [comment]
Hey @blake-enyart,

Thanks soo much for letting me know!

I may point some people to your videos if I need a quick explainer for some people. Appreciate the work.
