### ISSUE TITLE
Former2 Helper Failure

### ISSUE THREAD

**Issue by ben-haverly-cfa** [iann0036/former2#148]
I am receiving an error when trying to use the extension in Firefox:
"The call to the SDK failed. You may need to update the Former2 Helper extension."

When I try in Chrome it instead says ""No response from extension".

Any idea on this?

**Comment by iann0036** [comment]
Hey @ben-haverly-cfa,

Thanks for raising this. Looks like I missed an SDK update!

I've updated the helper extensions to 1.36 which have both the latest changes, and a more descriptive message on failure to indicate its cause. Let me know if that fixes your issue after updating.

**Comment by romislovs** [comment]
Hi,

I did Update the extension to 1.36, but still seeing errors (FF 85.0 (64-bit) Linux)
![Screenshot at 2021-02-12 09-33-09](https://user-images.githubusercontent.com/11667000/107746289-da59ef80-6d15-11eb-9454-ed81a5626871.png)

**Comment by romislovs** [comment]
Well, Lambda, IAM, Kinesis,codeBuild, Athena, Glue resources seem to work fine

**Comment by iann0036** [comment]
Hi all,

Thanks for the confirmations!

I do now spot that I had an issue during the packaging of the AWS SDK into the extension. Could you please try again with version 1.37 and let me know if those issues are fixed?

**Comment by romislovs** [comment]
Version 1.37 - works like a charm!

**Comment by ben-haverly-cfa** [comment]
Thanks! It doesn't look like version 1.37 is available currently on Chrome but it has worked on Firefox!
