### ISSUE TITLE
Environment, MountPoints, PortMappings, VolumesFrom not picked up on AWS::ECS::TaskDefinition

### ISSUE THREAD

**Issue by bgarssen** [iann0036/former2#15]
Hi Ian

When I generate a cloudformation template for a task definition these properties are not picked up. From the code I get that they are not filled in the data structures, the call is made to the API to pick them up. Would it be an option to add them ? 

Now I get something like this : 
```
    ecs7f93d16:
        Type: "AWS::ECS::TaskDefinition"
        Properties:
            ContainerDefinitions: 
              - 
                Cpu: 0
                Environment: {}
                Essential: true
                Image: "612516126697.dkr.ecr.eu-central-1.amazonaws.com/mn-jenkins"
                Memory: 512
                MountPoints: {}
                Name: "CD-Jenkins"
                PortMappings: {}
                Privileged: true
                User: "root"
                VolumesFrom: {}
            Family: "Task-Jenkins"
            TaskRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            ExecutionRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            NetworkMode: "bridge"
            Volumes: 
              - 
                Name: "CD-jenkins"
                DockerVolumeConfiguration: 
                    Scope: "task"
                    Driver: "local"
                    DriverOpts: 
                        device: "fs-3af18a63.efs.eu-central-1.amazonaws.com:/"
                        o: "addr=fs-3af18a63.efs.eu-central-1.amazonaws.com,nfsvers=4.0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
                        type: "nfs"
            RequiresCompatibilities: 
              - "EC2"

```

It would be a great enhancement that would save a lot of time when extracting cloudformation form an environment. 

Best
Bart

**Comment by iann0036** [comment]
Hi Bart,

Thanks heaps for raising. I couldn't determine what properties you are missing though. Could you let me know specifically which properties you believe should be there? It's very possible I've missed one or two.

**Comment by bgarssen** [comment]
Hi Ian

Thanks for coming back on the issue.

It's mainly the collection properties that are not generated.

So for this example :
    ecs65d9ab2:
        Type: "AWS::ECS::TaskDefinition"
        Properties:
            ContainerDefinitions:
              -
                Cpu: 0
                Environment: {}
                Essential: true
                Image: "612516126697.dkr.ecr.eu-central-1.amazonaws.com/mn-jenkins"
                Memory: 4096
                MemoryReservation: 512
                MountPoints: {}
                Name: "CD-Jenkins"
                PortMappings: {}
                Privileged: true
                User: "root"
                VolumesFrom: {}
            Family: "Task-Jenkins"
            TaskRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            ExecutionRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            NetworkMode: "bridge"
            Volumes:
              -
                Name: "CD-jenkins"
                DockerVolumeConfiguration:
                    Scope: "task"
                    Driver: "local"
                    DriverOpts:
                        device: "fs-3af18a63.efs.eu-central-1.amazonaws.com:/"
                        o: "addr=fs-3af18a63.efs.eu-central-1.amazonaws.com,nfsvers=4.0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
                        type: "nfs"
            RequiresCompatibilities:
              - "EC2"
            Memory: "4096"


The tool is not storing and generating :

  *   Environment (which contains the environment variables for the docker container with for example connnect strings to RDS databases)
  *   Mountpoints (containing the docker container mountpoints)
  *   PortMappings (incoming port mappings for the docker container)
  *   VolumesFrom - I am not quite sure what should be in there but it is probably something about the non-persistent volumes for ecs serverless.

Great tool by the way ! I use it to generate cloudformation scripts and then adapt them to relative scripts for rollout to different AWS environments (basically converting all hard coded values to !Ref like things and parameters and stuff).

best
Bart


________________________________
Van: Ian Mckay <notifications@github.com>
Verzonden: woensdag 26 juni 2019 10:09
Aan: iann0036/former2
CC: bgarssen; Author
Onderwerp: Re: [iann0036/former2] Environment, MountPoints, PortMappings, VolumesFrom not picked up on AWS::ECS::TaskDefinition (#15)


Hi Bart,

Thanks heaps for raising. I couldn't determine what properties you are missing though. Could you let me know specifically which properties you believe should be there? It's very possible I've missed one or two.

**Comment by iann0036** [comment]
Thanks Bart,

That helps heaps. Could I also bother you for the "Raw Output (Debug)" output for the above also?

**Comment by bgarssen** [comment]
Ian

Sure you can !

[
    {
        "id": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
        "type": "iam.role",
        "data": {
            "Path": "/",
            "RoleName": "ecsTaskExecutionRole",
            "RoleId": "AROAY5HGOL7UTFUEDJQBO",
            "Arn": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
            "CreateDate": "2019-05-07T13:15:23.000Z",
            "AssumeRolePolicyDocument": "%7B%22Version%22%3A%222008-10-17%22%2C%22Statement%22%3A%5B%7B%22Sid%22%3A%22%22%2C%22Effect%22%3A%22Allow%22%2C%22Principal%22%3A%7B%22Service%22%3A%22ecs-tasks.amazonaws.com%22%7D%2C%22Action%22%3A%22sts%3AAssumeRole%22%7D%5D%7D",
            "MaxSessionDuration": 3600,
            "Tags": []
        },
        "region": "eu-central-1"
    },
    {
        "id": "arn:aws:ecs:eu-central-1:612516126697:task-definition/Task-Jenkins:1",
        "type": "ecs.taskdefinition",
        "data": {
            "taskDefinitionArn": "arn:aws:ecs:eu-central-1:612516126697:task-definition/Task-Jenkins:1",
            "containerDefinitions": [
                {
                    "name": "CD-Jenkins",
                    "image": "612516126697.dkr.ecr.eu-central-1.amazonaws.com/mn-jenkins",
                    "cpu": 0,
                    "memory": 512,
                    "portMappings": [
                        {
                            "containerPort": 8080,
                            "hostPort": 80,
                            "protocol": "tcp"
                        }
                    ],
                    "essential": true,
                    "environment": [],
                    "mountPoints": [
                        {
                            "sourceVolume": "CD-jenkins",
                            "containerPath": "/var/jenkins_home"
                        }
                    ],
                    "volumesFrom": [],
                    "user": "root",
                    "privileged": true,
                    "ulimits": [
                        {
                            "name": "nofile",
                            "softLimit": 32000,
                            "hardLimit": 65536
                        }
                    ],
                    "logConfiguration": {
                        "logDriver": "awslogs",
                        "options": {
                            "awslogs-group": "/ecs/CD-stack",
                            "awslogs-region": "eu-central-1",
                            "awslogs-stream-prefix": "ecs"
                        }
                    }
                }
            ],
            "family": "Task-Jenkins",
            "taskRoleArn": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
            "executionRoleArn": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
            "networkMode": "bridge",
            "revision": 1,
            "volumes": [
                {
                    "name": "CD-jenkins",
                    "dockerVolumeConfiguration": {
                        "scope": "task",
                        "driver": "local",
                        "driverOpts": {
                            "device": "fs-3af18a63.efs.eu-central-1.amazonaws.com:/",
                            "o": "addr=fs-3af18a63.efs.eu-central-1.amazonaws.com,nfsvers=4.0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2",
                            "type": "nfs"
                        }
                    }
                }
            ],
            "status": "ACTIVE",
            "requiresAttributes": [
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
                },
                {
                    "name": "com.amazonaws.ecs.capability.privileged-container"
                },
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.25"
                },
                {
                    "name": "ecs.capability.execution-role-ecr-pull"
                },
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
                },
                {
                    "name": "com.amazonaws.ecs.capability.ecr-auth"
                },
                {
                    "name": "com.amazonaws.ecs.capability.task-iam-role"
                },
                {
                    "name": "ecs.capability.execution-role-awslogs"
                },
                {
                    "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
                },
                {
                    "name": "ecs.capability.docker-plugin.local"
                },
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
                }
            ],
            "placementConstraints": [],
            "compatibilities": [
                "EC2"
            ],
            "requiresCompatibilities": [
                "EC2"
            ]
        },
        "region": "eu-central-1"
    }
]

The info is in the debug logs as you can see.

best
Bart
________________________________
Van: Ian Mckay <notifications@github.com>
Verzonden: woensdag 26 juni 2019 10:33
Aan: iann0036/former2
CC: bgarssen; Author
Onderwerp: Re: [iann0036/former2] Environment, MountPoints, PortMappings, VolumesFrom not picked up on AWS::ECS::TaskDefinition (#15)


Thanks Bart,

That helps heaps. Could I also bother you for the "Raw Output (Debug)" output for the above also?

**Comment by bgarssen** [comment]
Ian

This is an example of an environment block. The jenkins task does not have that.

                    "environment": [
                        {
                            "name": "DB_TYPE",
                            "value": "postgresql"
                        },
                        {
                            "name": "DB_HOST",
                            "value": "cd-databases.chnnpf1ilzsk.eu-central-1.rds.amazonaws.com"
                        },
                        {
                            "name": "DB_PORT",
                            "value": "5432"
                        },
                        {
                            "name": "DB_USER",
                            "value": "artifactory"
                        },
                        {
                            "name": "DB_PASSWORD",
                            "value": "secret"
                        }
                    ],

Best
Bart

________________________________
Van: Bart Garssen <bgarssen@hotmail.com>
Verzonden: woensdag 26 juni 2019 10:42
Aan: iann0036/former2
Onderwerp: Re: [iann0036/former2] Environment, MountPoints, PortMappings, VolumesFrom not picked up on AWS::ECS::TaskDefinition (#15)

Ian

Sure you can !

[
    {
        "id": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
        "type": "iam.role",
        "data": {
            "Path": "/",
            "RoleName": "ecsTaskExecutionRole",
            "RoleId": "AROAY5HGOL7UTFUEDJQBO",
            "Arn": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
            "CreateDate": "2019-05-07T13:15:23.000Z",
            "AssumeRolePolicyDocument": "%7B%22Version%22%3A%222008-10-17%22%2C%22Statement%22%3A%5B%7B%22Sid%22%3A%22%22%2C%22Effect%22%3A%22Allow%22%2C%22Principal%22%3A%7B%22Service%22%3A%22ecs-tasks.amazonaws.com%22%7D%2C%22Action%22%3A%22sts%3AAssumeRole%22%7D%5D%7D",
            "MaxSessionDuration": 3600,
            "Tags": []
        },
        "region": "eu-central-1"
    },
    {
        "id": "arn:aws:ecs:eu-central-1:612516126697:task-definition/Task-Jenkins:1",
        "type": "ecs.taskdefinition",
        "data": {
            "taskDefinitionArn": "arn:aws:ecs:eu-central-1:612516126697:task-definition/Task-Jenkins:1",
            "containerDefinitions": [
                {
                    "name": "CD-Jenkins",
                    "image": "612516126697.dkr.ecr.eu-central-1.amazonaws.com/mn-jenkins",
                    "cpu": 0,
                    "memory": 512,
                    "portMappings": [
                        {
                            "containerPort": 8080,
                            "hostPort": 80,
                            "protocol": "tcp"
                        }
                    ],
                    "essential": true,
                    "environment": [],
                    "mountPoints": [
                        {
                            "sourceVolume": "CD-jenkins",
                            "containerPath": "/var/jenkins_home"
                        }
                    ],
                    "volumesFrom": [],
                    "user": "root",
                    "privileged": true,
                    "ulimits": [
                        {
                            "name": "nofile",
                            "softLimit": 32000,
                            "hardLimit": 65536
                        }
                    ],
                    "logConfiguration": {
                        "logDriver": "awslogs",
                        "options": {
                            "awslogs-group": "/ecs/CD-stack",
                            "awslogs-region": "eu-central-1",
                            "awslogs-stream-prefix": "ecs"
                        }
                    }
                }
            ],
            "family": "Task-Jenkins",
            "taskRoleArn": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
            "executionRoleArn": "arn:aws:iam::612516126697:role/ecsTaskExecutionRole",
            "networkMode": "bridge",
            "revision": 1,
            "volumes": [
                {
                    "name": "CD-jenkins",
                    "dockerVolumeConfiguration": {
                        "scope": "task",
                        "driver": "local",
                        "driverOpts": {
                            "device": "fs-3af18a63.efs.eu-central-1.amazonaws.com:/",
                            "o": "addr=fs-3af18a63.efs.eu-central-1.amazonaws.com,nfsvers=4.0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2",
                            "type": "nfs"
                        }
                    }
                }
            ],
            "status": "ACTIVE",
            "requiresAttributes": [
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.17"
                },
                {
                    "name": "com.amazonaws.ecs.capability.privileged-container"
                },
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.25"
                },
                {
                    "name": "ecs.capability.execution-role-ecr-pull"
                },
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
                },
                {
                    "name": "com.amazonaws.ecs.capability.ecr-auth"
                },
                {
                    "name": "com.amazonaws.ecs.capability.task-iam-role"
                },
                {
                    "name": "ecs.capability.execution-role-awslogs"
                },
                {
                    "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
                },
                {
                    "name": "ecs.capability.docker-plugin.local"
                },
                {
                    "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
                }
            ],
            "placementConstraints": [],
            "compatibilities": [
                "EC2"
            ],
            "requiresCompatibilities": [
                "EC2"
            ]
        },
        "region": "eu-central-1"
    }
]

The info is in the debug logs as you can see.

best
Bart
________________________________
Van: Ian Mckay <notifications@github.com>
Verzonden: woensdag 26 juni 2019 10:33
Aan: iann0036/former2
CC: bgarssen; Author
Onderwerp: Re: [iann0036/former2] Environment, MountPoints, PortMappings, VolumesFrom not picked up on AWS::ECS::TaskDefinition (#15)


Thanks Bart,

That helps heaps. Could I also bother you for the "Raw Output (Debug)" output for the above also?

**Comment by iann0036** [comment]
Cheers Bart,

Found the issues with that extra debug. I've updated former2.com with the fix but be aware the cache on the site is fairly aggressive, particularly on Chrome.

Give it a try and let me know if the fix works for you.

**Comment by bgarssen** [comment]
hi Ian

That looks brilliant !

AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    ecs859d172:
        Type: "AWS::ECS::TaskDefinition"
        Properties:
            ContainerDefinitions:
              -
                Environment:
                  -
                    Name: "DB_TYPE"
                    Value: "postgresql"
                  -
                    Name: "DB_HOST"
                    Value: "cd-databases.chnnpf1ilzsk.eu-central-1.rds.amazonaws.com"
                  -
                    Name: "DB_PORT"
                    Value: "5432"
                  -
                    Name: "DB_USER"
                    Value: "artifactory"
                  -
                    Name: "DB_PASSWORD"
                    Value: "secret"
                Essential: true
                Image: "612516126697.dkr.ecr.eu-central-1.amazonaws.com/mn-artifactory"
                Memory: 4096
                MemoryReservation: 512
                MountPoints:
                  -
                    SourceVolume: "CD-artifactory"
                    ContainerPath: "/var/opt/jfrog/artifactory"
                Name: "CD-Artifactory"
                PortMappings:
                  -
                    ContainerPort: 8081
                    HostPort: 8081
                    Protocol: "tcp"
            Family: "Task-Artifactory"
            TaskRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            ExecutionRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            NetworkMode: "bridge"
            Volumes:
              -
                Name: "CD-artifactory"
                DockerVolumeConfiguration:
                    Scope: "task"
                    Driver: "local"
                    DriverOpts:
                        device: "fs-6086c539.efs.eu-central-1.amazonaws.com:/"
                        o: "addr=fs-6086c539.efs.eu-central-1.amazonaws.com,nfsvers=4.0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
                        type: "nfs"
            RequiresCompatibilities:
              - "EC2"

    ecs7f93d16:
        Type: "AWS::ECS::TaskDefinition"
        Properties:
            ContainerDefinitions:
              -
                Essential: true
                Image: "612516126697.dkr.ecr.eu-central-1.amazonaws.com/mn-jenkins"
                Memory: 512
                MountPoints:
                  -
                    SourceVolume: "CD-jenkins"
                    ContainerPath: "/var/jenkins_home"
                Name: "CD-Jenkins"
                PortMappings:
                  -
                    ContainerPort: 8080
                    HostPort: 80
                    Protocol: "tcp"
                Privileged: true
                User: "root"
            Family: "Task-Jenkins"
            TaskRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            ExecutionRoleArn: "arn:aws:iam::612516126697:role/ecsTaskExecutionRole"
            NetworkMode: "bridge"
            Volumes:
              -
                Name: "CD-jenkins"
                DockerVolumeConfiguration:
                    Scope: "task"
                    Driver: "local"
                    DriverOpts:
                        device: "fs-3af18a63.efs.eu-central-1.amazonaws.com:/"
                        o: "addr=fs-3af18a63.efs.eu-central-1.amazonaws.com,nfsvers=4.0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
                        type: "nfs"
            RequiresCompatibilities:
              - "EC2"

That will save me a lot of time 🙂

Many thanks !

Best
Bart
________________________________
Van: Ian Mckay <notifications@github.com>
Verzonden: woensdag 26 juni 2019 11:05
Aan: iann0036/former2
CC: bgarssen; Author
Onderwerp: Re: [iann0036/former2] Environment, MountPoints, PortMappings, VolumesFrom not picked up on AWS::ECS::TaskDefinition (#15)


Cheers Bart,

Found the issues with that extra debug. I've updated former2.com with the fix but be aware the cache on the site is fairly aggressive, particularly on Chrome.

Give it a try and let me know if the fix works for you.

**Comment by iann0036** [comment]
You're very welcome. If you see any others like this, feel free to raise.
