### ISSUE TITLE
Add AppFlow service in the README

### ISSUE THREAD

**Issue by ddsantana** [iann0036/former2#152]
Hi, I just extracted YAML from AppFlow using former2, but note that this service is not listed in README.md.

Therefore, I suggest adding the AppFlow service to the README.

![image](https://user-images.githubusercontent.com/79486997/108784867-09ab0080-754f-11eb-9e7b-cb588d21b067.png)

**Comment by iann0036** [comment]
Hi @ddsantana,

Thanks for raising! I've regenerated the list and pushed that update.

As a note more for my future self, I generated this list via the following:

```
"* " + sections.map(x => x.service.replace(/\s/g, "").replace(/\,/g, "").replace(/\-/g, "").replace(/\&amp\;/g, "And")).sort().join(`\n* `)
```
