### ISSUE TITLE
Generate References instead of absolute ARNs

### ISSUE THREAD

**Issue by Murcho** [iann0036/former2#17]
This is probably going to be way too difficult but I thought I'd throw the idea out there.

In CloudFormation stacks you can use Ref: and Fn::GetAtt to pull dynamic information from other resources. Would it be feasible or even possible to generate the References or attribute fetchers instead of populating with the full ARN?

**Comment by iann0036** [comment]
Former2 already does this for some resources: https://github.com/iann0036/former2/blob/master/js/mappings.js#L2311

You're right in that there's a chunk of work to map all return values for all resources. If you have a specific type you want covered, let me know and I'll prioritise.

**Comment by Murcho** [comment]
Oh wow, that is one enormous file!

Right now I'm trying to extract a Cognito User Pool with a Federated Identity Pool.  The Federated Identity Pool needs to map the authentication provider details from the Cognito User pool along with the IAM Roles and attached managed Policies.

Former2 got me a large part of the way there so thanks for the work! I'm just doing the above by hand right now.

**Comment by iann0036** [comment]
Added the return value mappings for those mentioned resources. Still a bit to do that I won't track here but if you have further types you'd like prioritised, let me know.

If your expected output still isn't right also let me know :)
