### ISSUE TITLE
AWS::SSO::Assignment no results

### ISSUE THREAD

**Issue by anderssonpof** [iann0036/former2#170]
Scanning for assignments seems to quietly fail for me.

I would guess that having a lot of assignment might be the cause of this
Checked the background page for the extension

sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()
sso.eu-central-1.amazonaws.com/:1 Failed to load resource: the server responded with a status of 400 ()

Let me know if you need more info

**Comment by iann0036** [comment]
Hi @anderssonpof,

Thanks for raising! Could you confirm if your AWS SSO instance is deployed in `eu-central-1` or elsewhere? Also do you happen to get back Permission Sets?

**Comment by anderssonpof** [comment]
eu-central-1 is correct.
PermissionSets show up

**Comment by iann0036** [comment]
Thanks for that @anderssonpof,

I think I've identified the issue (an unfortunate typo!). Could you try again now?

**Comment by anderssonpof** [comment]
@iann0036 perfect!

It is now populating. However no terraform is generated.
Cloudformation and Troposphere does generate though

Terraform output:
# No resources generated

**Comment by iann0036** [comment]
Terraform isn't currently supported for all resources, however I'm happy to prioritise that one for you.

Should be in place now.

**Comment by anderssonpof** [comment]
@iann0036 Thanks a lot! 👍 
Much appreciated
