### ISSUE TITLE
ECR does not list repositories

### ISSUE THREAD

**Issue by suryafx** [iann0036/former2#18]
Clicking on Compute - ECR shows up empty.

**Comment by iann0036** [comment]
Hi,

Thanks for raising. I believe the referenced commit should fix this for you - though you may need to clear your cache if you want to try it in the next hour or two.

If that still doesn't work, please let me know if you see anything in your console - if so, copy the error ensuring to sanitise anything sensitive.

Cheers,
Ian.

**Comment by suryafx** [comment]
It is fixed now. Thanks!
