### ISSUE TITLE
Support of ApiGatewayV2::VpcLink

### ISSUE THREAD

**Issue by andriibu-ownid** [iann0036/former2#180]
It seems that [VpcLink for ApiGatewayV2](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-vpclink.html) isn't discovered by Former2.

I created the HTTP API and VPC link via AWS Console.
It's discoverable using CLI `aws apigatewayv2 get-vpc-link --vpc-link-id xxxxx`

```
{
    "CreatedDate": "2021-09-13T11:50:08+00:00",
    "Name": "xxxxx-dev-http",
    "SecurityGroupIds": [
        "sg-xxx",
        "sg-yyy",
        "sg-zzz"
    ],
    "SubnetIds": [
        "subnet-xxx",
        "subnet-xxx",
        "subnet-xxx",
        "subnet-xxx"
    ],
    "Tags": {},
    "VpcLinkId": "XXXXX",
    "VpcLinkStatus": "AVAILABLE",
    "VpcLinkStatusMessage": "VPC link is ready to route traffic",
    "VpcLinkVersion": "V2"
}


```

But former2 doesn't recognize it, and shows only links with `Type: "AWS::ApiGateway::VpcLink"`

**Comment by iann0036** [comment]
Hey @andriibu-ownid,

Thanks heaps for raising!

Looks like there was a small casing error causing this. Should be fixed now, but let me know otherwise.

**Comment by andriibu-ownid** [comment]
Yeah, it works! Great thanks.
