### ISSUE TITLE
AWS::Config::RemediationConfiguration not detecting resources

### ISSUE THREAD

**Issue by OttawaCloudConsulting** [iann0036/former2#184]
All Config resources appear after scan.

Remediation tab is empty.

Tested at https://former2.com with IAM Role with full AWS Administrator Permissions

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/60020004/135119811-95f4f403-0a82-4610-8696-6875ee0ad723.png">

Checked in RESOURCE_COVERAGE.md that coverage is listed for "AWS::Config::RemediationConfiguration"

**Comment by iann0036** [comment]
Hey @OttawaCloudConsulting,

Thanks for raising!

I think I picked up on a dumb typo. Could you retest this?

**Comment by OttawaCloudConsulting** [comment]
Tested and still not showing remediation:
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/60020004/135294248-2499e5a8-1cb5-42ff-a688-ceb16a9f3515.png">

Expected remediation:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/60020004/135294599-ca5a16d0-b899-4ef2-b85e-abc72b0c05ce.png">

**Comment by iann0036** [comment]
Hey @OttawaCloudConsulting,

I tested this myself and it seems to work with my manual remediation. Could you check you have the region correctly set, if the associated config rule is there, and if there are any errors in your browser? (View -> Developer -> JavaScript Console on Chrome).

**Comment by OttawaCloudConsulting** [comment]
I can confirm that the region is correct, and I just tested with the following steps using Firefox.

1. Navigate AWS and confirm Config Rule
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/60020004/135613248-a7a1a74c-51c9-41d1-b8a8-62f1cca74f01.png">

1. Clear cache
2. https://former2.com/
3. Set Region Canada & Enter IAM Credentials
4. Scan Resources
5. Select Config Rule
<img width="1755" alt="image" src="https://user-images.githubusercontent.com/60020004/135613306-996ee4a9-74aa-489b-b31f-164b6ae4cc9f.png">

6. Remediation Rule tab empty
<img width="970" alt="image" src="https://user-images.githubusercontent.com/60020004/135613360-6583833d-4be8-4692-a928-ff4c988d6b7d.png">

Firefox Console output:
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/60020004/135613400-c68e2dbd-bbe9-4f46-86f0-70c6b3462c08.png">

**Comment by iann0036** [comment]
Thanks @OttawaCloudConsulting,

Had a deeper dig. Found out that the likely issue is that a subsequent rule without a remediation was incorrectly clearing the table (and is why I couldn't originally replicate!).

Give it another shot now?

**Comment by OttawaCloudConsulting** [comment]
Checked and it works now :)

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/60020004/135617642-650d88a3-0c68-4b2f-8697-d9a0ae13dda2.png">
