### ISSUE TITLE
Compute - ECS - Task Definitions always empty

### ISSUE THREAD

**Issue by suryafx** [iann0036/former2#19]
Compute - ECS - Task Definitions always empty

**Comment by iann0036** [comment]
Hi,

Thanks for raising. I personally couldn't replicate this. It's possible your specific ECS Task Definition has something that is breaking an assumption.

Please let me know if you see anything in your console - if so, copy the error ensuring to sanitise anything sensitive. If there isn't any console errors, could you let me know if there is anything special about the task definitions in your account?

Also, check to ensure region is correct.

Cheers,
Ian.

**Comment by suryafx** [comment]
Now I see that same task getting repeated multiple times and does not list other tasks.

![image](https://user-images.githubusercontent.com/44353588/65830640-d9662080-e2ce-11e9-9999-a71a6060df11.png)

**Comment by iann0036** [comment]
Oh wow. Looks like it was taking in all versions of a single task definition. I've amended to only take the latest one. Let me know how that goes.

**Comment by suryafx** [comment]
It worked. Thanks!

**Comment by suryafx** [comment]
Former2 is an amazing tool. I am loving using it. 
Thanks for looking into these issues right a way.
