### ISSUE TITLE
ECR for terraform drops "name" attribute from aws_ecr_repository

### ISSUE THREAD

**Issue by suryafx** [iann0036/former2#20]
CloudFormation
==========================================
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    ecrcab9c80:
        Type: "AWS::ECR::Repository"
        Properties:
            RepositoryName: "test-api"
            name: "test-api"
            LifecyclePolicy: 
                RegistryId: "583566476015"

    ecsdc66eaf:
        Type: "AWS::ECS::Cluster"
        Properties:
            ClusterName: "test-api-staging"
==========================================
Same output when Terraform is selected shows up as

provider "aws" {
    region = "us-east-1"
}

resource "aws_ecr_repository" "ecrcab9c80" {}

resource "aws_ecs_cluster" "ecsdc66eaf" {
    name = "test-api-staging"
}

**Comment by iann0036** [comment]
Thanks! Looks like that 'name' property was assigned to the CloudFormation output instead of the Terraform output.
