### ISSUE TITLE
MediaLive Services Not Being Discovered

### ISSUE THREAD

**Issue by jwryan1988** [iann0036/former2#200]
Great tool!  Thanks for developing this. 

I noticed MediaLive services are not being discovered.  I've tested in Chrome and Edge with the extensions installed.

**Comment by iann0036** [comment]
Hey @jwryan1988,

Thanks for raising!

It looks like although the Former2 programming seems correct, the permissions required to retrieve the resources aren't in the `ReadOnlyAccess` policy. You may want to add `AWSElementalMediaLiveReadOnly` to your user / role to have this work until AWS fixes the ReadOnlyAccess` policy.

Let me know how that goes.

**Comment by jwryan1988** [comment]
That did the trick. Thank you!
