### ISSUE TITLE
 An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the │ argument value.

### ISSUE THREAD

**Issue by ishanrakitha** [iann0036/former2#203]
Hi All,

I'm new to Former2. Exported my entire AWS environment to Terraform. 
Could you please advise on the error highlighted within tag section of EC2, EFS. 

Appreciate your support in advance.  

![1](https://user-images.githubusercontent.com/3178753/143894676-853c6dae-7aa1-487a-b2de-f3fba46cc278.JPG)
![2](https://user-images.githubusercontent.com/3178753/143894681-6c3c63ca-0ea5-47cc-8be2-16bbaf4f3dee.JPG)

Thank you.

**Comment by ishanrakitha** [comment]
As per the AWS documentation Amazon EFS applies the aws:elasticfilesystem:default-backup system tag key with a value of enabled to EFS file systems when automatic backups are enabled.

**Comment by iann0036** [comment]
Hey @ishanrakitha,

Thanks for raising!

I've added an update which should hopefully filter any `aws:` prefixed tags from all resources. Let me know if this work for you.

**Comment by ishanrakitha** [comment]
Thank you so much @iann0036 . 

Tested just now, And i'm etting the following error on terraform init.

Please advise. Thank you very much. 

![image](https://user-images.githubusercontent.com/3178753/144744107-913682da-5134-4a68-93bb-94785503c53e.png)

**Comment by iann0036** [comment]
Hey @ishanrakitha,

Thanks for raising. I've added an escape for `${` in Terraform strings. Let me know how that goes for you.

**Comment by ishanrakitha** [comment]
Thank you @iann0036 

Now its working as expected. 

![image](https://user-images.githubusercontent.com/3178753/144835478-5edc5cdb-d24c-4af1-93b3-06cfff94107e.png)
