### ISSUE TITLE
Terraform output "No Resources Generated"

### ISSUE THREAD

**Issue by mrlivingston719** [iann0036/former2#205]
Hi, I've tried from chrome, firefox, and MS Edge, I get the same result in all 3 browsers. I'm unable to generate Terraform output code. Cloudformation works great, everything else seems to be ok as well.

Here's the raw debug output with account numbers removed. Thank you very much for any help you can provide!

[
    {
        "id": "arn:aws:imagebuilder:us-west-2:XXXXXXXXXX:image-pipeline/rhel-base-image-pipeline",
        "type": "ec2imagebuilder.imagepipeline",
        "data": {
            "arn": "arn:aws:imagebuilder:us-west-2:XXXXXXXXXX:image-pipeline/rhel-base-image-pipeline",
            "name": "RHEL-Base-Image-Pipeline",
            "description": "Pipeline designed to create base RHEL-8 AMI",
            "platform": "Linux",
            "enhancedImageMetadataEnabled": true,
            "imageRecipeArn": "arn:aws:imagebuilder:us-west-2:XXXXXXXXXX:image-recipe/rhel-8-4-base/0.0.1",
            "infrastructureConfigurationArn": "arn:aws:imagebuilder:us-west-2:XXXXXXXXXX:infrastructure-configuration/rhel-08-base-image-infrastructure-configuration",
            "imageTestsConfiguration": {
                "imageTestsEnabled": false,
                "timeoutMinutes": 90
            },
            "schedule": {
                "scheduleExpression": "cron(0 0 * * ? *)",
                "pipelineExecutionStartCondition": "EXPRESSION_MATCH_ONLY"
            },
            "status": "ENABLED",
            "dateCreated": "2021-11-18T20:51:00.934Z",
            "dateUpdated": "2021-11-18T20:51:00.934Z",
            "dateLastRun": "2021-12-01T00:00:30.848Z",
            "dateNextRun": "2021-12-02T00:00:00.000Z",
            "tags": {}
        },
        "region": "us-west-2"
    }
]

**Comment by mrlivingston719** [comment]
I found the support matrix, and ImageBuilder is not supported for Terraform output at this time...I apologize for raising this issue without researching that first.

**Comment by kjhosein** [comment]
For anyone else looking for the 'support matrix' that @mrlivingston719 referred to, it's here:

[https://github.com/iann0036/former2/blob/master/RESOURCE_COVERAGE.md](https://github.com/iann0036/former2/blob/master/RESOURCE_COVERAGE.md)
