### ISSUE TITLE
Not ale to generate the CFN scripts for App Mesh

### ISSUE THREAD

**Issue by praveensripati** [iann0036/former2#207]
When scanning the App Mesh resources, getting the below error. The code and the SDK input parameters are not in sync.

Error calling AppMesh.describeVirtualNode
There were 2 validation errors: * MissingRequiredParameter: Missing required key 'virtualNodeName' in params * UnexpectedParameter: Unexpected key 'virtualNode' found in params

**Comment by iann0036** [comment]
Hey @praveensripati,

Thanks for raising!

I've fixed up that typo so hopefully that should work now. Let me know how it goes.

**Comment by praveensripati** [comment]
@iann0036 - Works like charm.
