### ISSUE TITLE
ECS Task Definition fails to generate output in terraform but works for CloudFormation

### ISSUE THREAD

**Issue by suryafx** [iann0036/former2#21]
![image](https://user-images.githubusercontent.com/44353588/65831261-6b712780-e2d5-11e9-8f29-641f88d38f57.png)

![image](https://user-images.githubusercontent.com/44353588/65831267-775ce980-e2d5-11e9-8c16-7f8e8c57a2d7.png)

**Comment by suryafx** [comment]
![image](https://user-images.githubusercontent.com/44353588/65831275-8d6aaa00-e2d5-11e9-867c-6125b54421fe.png)

**Comment by iann0036** [comment]
Cheers. This is one of the resources not yet mapped: https://github.com/iann0036/former2/blob/master/RESOURCE_COVERAGE.md#terraform-coverage

I'll prioritise this one for you.

**Comment by suryafx** [comment]
Thanks for sharing the mapped list. I missed that one. 
I know this is a lot of stuff take care of with AWS and converting scripts into so many output formats. You are doing an awesome job!
