### ISSUE TITLE
CloudFrontFunction map keys must be strings

### ISSUE THREAD

**Issue by bborup** [iann0036/former2#212]
"[/Resources/CloudFrontFunction/Type/FunctionCode] map keys must be strings; received numeric [0] instead"

AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    CloudFrontFunction:
        Type: "AWS::CloudFront::Function"
        Properties:
            Name: "ra-redirect"
            AutoPublish: false
            FunctionCode: 
                0: 102
                1: 117
                2: 110
                3: 99
                4: 116
                5: 105
                6: 111
                7: 110
                8: 32
                9: 104
                10: 97
                11: 110
                12: 100
             ...
    
Any ideas on what is causing this?

BTW, this is an outstanding utility.  We use it continually.

Thanks.

**Comment by iann0036** [comment]
Hey @bborup,

Thanks for raising!

I can't replicate this one locally. Could you confirm whether you're using the former2.com site directly or if you're using a local copy (or the CLI)? If using a local copy, could you also confirm whether you've updated to latest as the fix for this came in [around 3 months ago](https://github.com/iann0036/former2/commit/25bedb071bce730241de6fa16e0e9b88e024a224)?

If you're using the hosted site or latest, could you let me know your browser / OS combo also?

**Comment by bborup** [comment]
Ian,

Thank you for your quick reply.

We are using the CLI.  The version is 0.2.60.  We installed it on
12/2/2021.  We're running it on Windows 10.

Here is a snip of the function handler for "ra-direct".  It looks like it
is being serialized into decimal numbers for each character.  Is that
possible?

function handler(event) {
    var request = event.request,
        uri = request.uri;

    return {
        statusCode: 302,
        statusDescription: "Found",
        headers: {
            location: {
                value: 'https://www.researchaffiliates.com' + uri
            },
        },
    };
}

Thanks,

Blake

**Comment by bborup** [comment]
Ian,

Thanks.  That fixed the issue.

**Comment by bborup** [comment]
Ian,

I'm sorry.  The template is now correctly formed, but I didn't notice that the "FunctionCode" is now empty:

    CloudFrontFunction3:
        Type: "AWS::CloudFront::Function"
        Properties:
            Name: "ra-redirect"
            AutoPublish: false
            FunctionCode: ""
            FunctionConfig: 
                Comment: ""
                Runtime: "cloudfront-js-1.0"

**Comment by iann0036** [comment]
Hey @bborup,

Thanks for letting me know. The SDK is particularly picky with the way it handles this specific field.

I should have a better fix for you in 0.2.62. Upgrade to this and let me know how you go.

**Comment by bborup** [comment]
Ian,

This looks good.  Let us test it and get back to you.

Regards.

**Comment by bborup** [comment]
Ian,

Sorry I'm late on this feedback.  We're almost there.

Two items that CloudFormation complains about:

1) AWS::CloudFront::CachePolicy empty "CookiesConfig{}" and
"QueryStringsConfig{}"
2) AWS::CloudFront::Function missing "FunctionConfig"

Thanks again for all your help.

Regards,

Blake

**Comment by iann0036** [comment]
Hey @bborup,

Should have both of those fixed in 0.2.68 for you. Do check the Cookies / QueryString issues though as I didn't have test data available to me.

**Comment by bborup** [comment]
As always, thanks for your quick response.

"FunctionConfig" is now there, but the other two are still empty.

Is there anything I can do to help you address this?

**Comment by iann0036** [comment]
Hey @bborup,

Thanks for checking that out for me. Looks like that needed some extra work. This should now be fully fixed in 0.2.69.

**Comment by bborup** [comment]
CloudFrontOriginRequestPolicy2:
Type: "AWS::CloudFront::OriginRequestPolicy"
Properties:
OriginRequestPolicyConfig:
Name: "all-headers-cookies-qstr"
Comment: ""
HeadersConfig:
HeaderBehavior: "allViewer"
CookiesConfig: {}
QueryStringsConfig: {}

**Comment by iann0036** [comment]
Thanks for sending that, seems odd.

Could you send me a sanitized version of the `--output-debug` for this resource?

**Comment by bborup** [comment]
Ian,

I'm sorry, but I don't know what you mean by --ouput-debug.  Can you send
me an example of the command line?

**Comment by iann0036** [comment]
Apologies, I meant to say `--output-raw-data`. The CLI command would be:

```
former2 generate --output-raw-data out.json --services CloudFront
```

**Comment by bborup** [comment]
[cloudfront.txt](https://github.com/iann0036/former2/files/8191049/cloudfront.txt)
(wouldn't let me upload .json)

**Comment by iann0036** [comment]
Hey @bborup,

Thanks for sending that through. I believe I spotted the issue, which was a plural typo. Give it another shot in 0.2.70.

**Comment by bborup** [comment]
That's fixed.  Thanks.

One last thing.  But I don't know if this is something you can handle.

"f2type": "cloudfront.function" entries appear to be duplicated.  But I'm wondering if the "stage": "DEVELOPMENT" is not correct for one of the duplicates.  There don't appear to be any with "stage": "LIVE", which there are in the account.

I've reatached the raw data file

[cloudfront.txt](https://github.com/iann0036/former2/files/8199763/cloudfront.txt)

**Comment by iann0036** [comment]
Hey @bborup,

Nice catch! Turns out CloudFront.listFunctions returns both the DEVELOPMENT and LIVE stages, but gets confused as the CloudFormation resource only wants one, with a combination of DEVELOPMENT and LIVE being represented by the `AutoPublish` property.

I've modified the behaviour to only show the latest stage for a single function in the table, and set `AutoPublish: true` when it's LIVE. Let me know if you think the behaviour should be different.

**Comment by bborup** [comment]
Ian,

That sounds good.

Thanks.

**Comment by bborup** [comment]
Ian,

Sorry to bother you, but did you make the change you mentioned?

Thanks.

**Comment by iann0036** [comment]
Hey @bborup,

Apologies, I didn't bump the CLI. Should be in now as 0.2.71.
