### ISSUE TITLE
Can't Import ec2 security group to Terraform - tags is missing equal sign

### ISSUE THREAD

**Issue by Georgeforman3** [iann0036/former2#216]
<img width="441" alt="Screen Shot 2022-02-28 at 11 34 46" src="https://user-images.githubusercontent.com/100565446/155959526-83a50834-1196-4965-abc5-ea903fdd6626.png">

Former2 generates the security group resource, I imported it with 'terraform import' command, ran 'terraform plan' and got the following error:
Blocks of type "tags" are not expected here. Did you mean to define argument "tags"? If so, use the equals sign to assign it a value.

I think it happens since 'tags' is a map attribute rather than a nested configuration block:
https://github.com/hashicorp/terraform/issues/19325

**Comment by iann0036** [comment]
Hey @Georgeforman3,

Thanks for raising!

I wasn't aware Terraform moved into this slightly different handling. I've added a pattern to express the difference between the blocks and maps in the latest release, but only for EC2 security groups at the moment. Are you aware if this is a global issue across all resources and if this issue exists for fields beyond `tags`?

**Comment by Georgeforman3** [comment]
@iann0036 Thanks for the quick reply!
Yes, from what I can tell it's a global issue across all resources for 'tags'. I still didn't encounter the issue for other fields.

**Comment by Georgeforman3** [comment]
@iann0036  It works now! Thanks!
