### ISSUE TITLE
Can't Import ec2 security group to Terraform when protocol is -1

### ISSUE THREAD

**Issue by Georgeforman3** [iann0036/former2#217]
![WhatsApp Image 2022-02-28 at 12 06 55](https://user-images.githubusercontent.com/100565446/155964332-e6e936a4-dcfb-4881-ac41-4d87a8eef460.jpeg)

Former2 generates the security group resource, I imported it with 'terraform import' command, ran 'terraform plan' and got the following error:

![WhatsApp Image 2022-02-28 at 12 08 18](https://user-images.githubusercontent.com/100565446/155964492-79da1881-1a18-4bff-826f-13da085a2407.jpeg)

I see that if the protocol is "-1" the 'from_port' and 'to_port' are required :
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#protocol

**Comment by iann0036** [comment]
Hey @Georgeforman3,

Thanks for raising!

I've added code to handle this case specifically in Terraform, and that should be available now. Let me know if that fixes your issue.

**Comment by Georgeforman3** [comment]
@iann0036  It works now! Thanks!!
