### ISSUE TITLE
AWS::IoTSiteWise::Asset Not Being Discovered

### ISSUE THREAD

**Issue by PtolemaiosII** [iann0036/former2#219]
Hi, thanks for developing on this great tool.

I just noticed when scanning, **AWS::IoTSiteWise::Asset** are not being discovered yet not be able to generate in output. While **AWS::IoTSiteWise::AssetModel** can be successfully discovered.
I've tested in both Chrome and Edge with helper installed.

**Comment by iann0036** [comment]
Hi @PtolemaiosII,

Thanks for raising!

I've pushed a change that should hopefully fix the assets not being discovered. Could you test this out and let me know if the assets now come up?
