### ISSUE TITLE
Terraform export for Glue Jobs

### ISSUE THREAD

**Issue by hrpitta** [iann0036/former2#220]
First of all! Thank you so much for the amazing tool you are creating! I don't know if it's on the improvement list and if it's an important feature for the Community but it's going to be amazing if you can add the Terraform format for the Glue jobs.
Thanks again for all the amazing job and hard work.

**Comment by iann0036** [comment]
Hey @hrpitta,

Thanks for raising!

I've added the Terraform output for Glue jobs specifically. Let me know how you go testing that and if there's auxiliary Glue resources you need.

**Comment by hrpitta** [comment]
Hey @iann0036 amazing!! Just tested and it's working perfectly!!
