### ISSUE TITLE
EMR keeps loading

### ISSUE THREAD

**Issue by OndatraMuz** [iann0036/former2#226]
Hi, all the resources I've tried seems to load without any problems but EMR never displays any resources and if it does then there is still the rotating loading circle so nothing can be selected. Tried to wait for several hours with no success.

**Comment by iann0036** [comment]
Hey @OndatraMuz,

Thanks for raising!

It should never usually take more than a minute or two to completely load your resources list (unless it's monstrously large) so there's probably a bug somewhere.

Could you open your browsers console and see if there are significant errors that may be related? In Chrome, you can do this by going to View -> Developer -> JavaScript Console.

**Comment by OndatraMuz** [comment]
Hey Ian, thanks for your quick response. 
The list could be actually monstrously large as there are hundreds of terminated emr clusters and it seems there is no way to reduce it except filtering by "active", maybe something like that could be implemented?
When I inspect my browser console mostly there are successful POST requests elasticmapreduce but some of them are failing with "400
Bad Request" and in the response ""__type	"ThrottlingException" message	"Rate exceeded""". 
Cheers

**Comment by iann0036** [comment]
Hey @OndatraMuz,

I've added that state filter as you suggested. Could you give it another try?

**Comment by OndatraMuz** [comment]
Hi Ian, worked like a charm, many thanks for your help!
