### ISSUE TITLE
StateMachine Retry Field Incorrectly Formatted

### ISSUE THREAD

**Issue by bborup** [iann0036/former2#233]
Step Functions::StateMachine
    Properties
        DefinitionString
            States
                Retry field is miss-formatted.
Example:
https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html#error-handling-examples - Handling a failure using Retry

This is the example from AWS:
{
   "Comment": "A Hello World example of the Amazon States Language using an AWS Lambda function",
   "StartAt": "HelloWorld",
   "States": {
      "HelloWorld": {
         "Type": "Task",
         "Resource": "arn:aws:lambda:us-east-1:123456789012:function:FailFunction",
         "Retry": [ {
            "ErrorEquals": ["HandledError"],
            "IntervalSeconds": 1,
            "MaxAttempts": 2,
            "BackoffRate": 2.0
         } ],
      "End": true
      }
   }
}

However, our Retry field is formatted:
{
   "Comment": "A Hello World example of the Amazon States Language using an AWS Lambda function",
   "StartAt": "HelloWorld",
   "States": {
      "HelloWorld": {
         "Type": "Task",
         "Resource": "arn:aws:lambda:us-east-1:123456789012:function:FailFunction"
   ,      "Retry": [ {
            "ErrorEquals": ["HandledError"],
            "IntervalSeconds": 1,
            "MaxAttempts": 2,
            "BackoffRate": 2.0
         } ],
      "End": true
      }
   }
}

Note the comma "," is not at the end of the Resource line, but on the following line.  Moving the comma to the end of the Resource line solves the format error.

**Comment by bborup** [comment]
{
        "f2id": "arn:aws:states:us-west-2:613624575854:stateMachine:stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
        "f2type": "stepfunctions.statemachine",
        "f2data": {
            "stateMachineArn": "arn:aws:states:us-west-2:613624575854:stateMachine:stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
            "name": "stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
            "status": "ACTIVE",
            "definition": " {\"Comment\":\"Triggers snapshot backup for Aurora clusters\",\n \"StartAt\":\"TakeSnapshots\",\n \"States\":{\n   \"TakeSnapshots\":{\n     \"Type\":\"Task\",\n     \"Resource\": \"arn:aws:lambda:us-west-2:613624575854:function:AuroraProdReplication-lambdaTakeSnapshotsAurora-GPTJYJPN566E\"\n,     \"Retry\":[\n       {\n       \"ErrorEquals\":[ \n         \"SnapshotToolException\"\n       ],\n       \"IntervalSeconds\":300,\n       \"MaxAttempts\":20,\n       \"BackoffRate\":1\n     },\n     {\n      \"ErrorEquals\":[ \n         \"States.ALL\"], \n         \"IntervalSeconds\": 30,\n         \"MaxAttempts\": 20,\n         \"BackoffRate\": 1\n     }\n    ],\n    \"End\": true \n   }\n }}",
            "roleArn": "arn:aws:iam::123456789123:role/AuroraProdReplication-iamroleStateExecution-1X8N78VPV33J9",
            "type": "STANDARD",
            "creationDate": "2019-11-21T17:37:39.053Z",
            "Tags": null
        },
        "f2region": "us-west-2",
        "name": "stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
        "creationtime": "2019-11-21T17:37:39.053Z"
    },

**Comment by iann0036** [comment]
Very weird!

I've added a change to force a reformat of the definition as it comes through. Give that a shot and let me know.

**Comment by bborup** [comment]
Still the same.  But not to worry.  It's a simple edit.  We can live with it.  Thanks for your help.
   
 {
        "f2id": "arn:aws:states:us-west-2:613624575854:stateMachine:stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
        "f2type": "stepfunctions.statemachine",
        "f2data": {
            "stateMachineArn": "arn:aws:states:us-west-2:613624575854:stateMachine:stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
            "name": "stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
            "status": "ACTIVE",
            "definition": " {\"Comment\":\"Triggers snapshot backup for Aurora clusters\",\n \"StartAt\":\"TakeSnapshots\",\n \"States\":{\n   \"TakeSnapshots\":{\n     \"Type\":\"Task\",\n     \"Resource\": \"arn:aws:lambda:us-west-2:613624575854:function:AuroraProdReplication-lambdaTakeSnapshotsAurora-GPTJYJPN566E\"\n,     \"Retry\":[\n       {\n       \"ErrorEquals\":[ \n         \"SnapshotToolException\"\n       ],\n       \"IntervalSeconds\":300,\n       \"MaxAttempts\":20,\n       \"BackoffRate\":1\n     },\n     {\n      \"ErrorEquals\":[ \n         \"States.ALL\"], \n         \"IntervalSeconds\": 30,\n         \"MaxAttempts\": 20,\n         \"BackoffRate\": 1\n     }\n    ],\n    \"End\": true \n   }\n }}",
            "roleArn": "arn:aws:iam::123456789123:role/AuroraProdReplication-iamroleStateExecution-1X8N78VPV33J9",
            "type": "STANDARD",
            "creationDate": "2019-11-21T17:37:39.053Z",
            "Tags": null
        },
        "f2region": "us-west-2",
        "name": "stateMachineTakeSnapshotsAurora-aHkDjYrsMEOM",
        "creationtime": "2019-11-21T17:37:39.053Z"
    },
