### ISSUE TITLE
Cognito UserPool is not picking up the EnabledMfas setting

### ISSUE THREAD

**Issue by air2** [iann0036/former2#241]
Currently it ignores the  EnabledMfas setting I have both (SMS and OneTimeToken) enabled, but the setting is not generated.

(Great tool btw!!!!)

**Comment by iann0036** [comment]
Hey @air2,

Thanks for raising!

This one is a little difficult as there's no API to retrieve the available list for a user pool. What is available is to get the enabled options for a user, so I've configured it to hopefully provide the list as it sees it in users. Let me know if that doesn't work though.
