### ISSUE TITLE
CloudFormation Template for RDS Replica Instance - Missing and Extra Properties

### ISSUE THREAD

**Issue by ldu2** [iann0036/former2#251]
## Bug Report:
Hi @iann0036, Thanks a lot for this great tool! It gives me extra confidence when I export the infrastructure.

While I was generating the CloudFormation template for our RDS instance with its **read replica**, it doesn't seem to recognize the relationship between the two instances. It's exporting them independently. 

As in that, the read replica should have the `SourceDBInstanceIdentifier` property refer to the source instance (maybe `SourceRegion` if different region) and it also has the some of extra properties `BackupRetentionPeriod, DBName, MasterUsername, MasterUserPassword, and PreferredBackupWindow` which shouldn't exist for a read replica. 

### Current Output:
```
...
Resources:
...
      DBInstanceIdentifier: "xxxx-read-replica"
...
      MasterUsername: "USERNAME"
      MasterUserPassword: "REPLACEME"
      PreferredBackupWindow: "00:00-00:30"
      BackupRetentionPeriod: 0
...
```
### Expected:
```
...
Resources:
...
      DBInstanceIdentifier: "xxxx-read-replica"
...
      SourceDBInstanceIdentifier: !Ref MyMainDB
...
```

I went through each of the available property on the [AWS::RDS::DBInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html) doc and doubled checked with my current set up. That's all I could find with my settings. 

Please let me know if I was not using the tool correctly or it's an improvement we can make. Thanks a lot!

**Comment by iann0036** [comment]
Hey @ldu2,

Thanks heaps for raising!

This looks like a bit of a special case I hadn't considered (RDS was already a bit funky). Could you do me a favour and reply with a copy the contents of the **Raw Output (Debug)** template once you've generated a template with the two instances in them, but replace any sensitive information like account IDs, database names, usernames etc.

I'm specifically looking for the criteria that makes an instance a replica to follow an alternate logic for the output.

**Comment by ldu2** [comment]
Here is a copy of the Raw Output (Debug) of all the properties it generates with masked value. It does seem like it has the information about the replica and source instance. Let me know if you need anything else.
 
[masked_former2.txt](https://github.com/iann0036/former2/files/9073371/masked_former2.txt)

**Comment by iann0036** [comment]
Thanks for that @ldu2,

I've pushed a fix to include the `SourceDBInstanceIdentifier` and omit those noted other properties when the `ReadReplicaSourceDBInstanceIdentifier` is set in the API response. Let me know how that goes.

**Comment by ldu2** [comment]
Hey @iann0036, it looks great. It matches up with mine now. I think it's a good verification for both.
 
The only thing I want to bring up is the port number for the main instance. It seems like the it is referring to the replica's port,
`!GetAtt RDSDBInstance2.Endpoint.Port`.  (Sorry I masked it in the file.) I don't think it matters much? But I'd say it's probably makes more sense if they just have their own ports just by number instead of references.

Really appreciate it for taking care of this!

**Comment by iann0036** [comment]
Hey @ldu2,

This is where Former2 gets a little dumb and does references mostly by add order, as these references are automatic. If you add the resources in the reverse order, you may get a better result.

**Comment by ldu2** [comment]
Ha, interesting. Then I think we are good. Thanks again for setting this straight. Closing the issue.
