### ISSUE TITLE
VPC - GovCloud Failure

### ISSUE THREAD

**Issue by brodie11** [iann0036/former2#26]
Absolutely _**love**_ the tool so far.  I'm trying to reverse-engineer my VPC in GovCloud (US-Gov-West-1) and it's partially completing because the Client VPN service does not exist yet in GovCloud.  That blocks out the main VPC UI because the calls never succeed.  I can temporarily unblock the UI by modifying the CSS in the dev toolbar.

Is there a way to fix this behavior of services/features not yet existing in GovCloud?

**Comment by iann0036** [comment]
Hi Brodie,

Thanks for raising! I don't have access to a GovCloud account so I can't test for you, but I added some handling that might fix that loading issue. Let me know how that goes for you and if you're still experiencing issues, can you grab any errors from the Console and paste them here (sanitised)?

**Comment by brodie11** [comment]
That did it!  So impressed how quickly you responded and fixed that!
