### ISSUE TITLE
Refresh the scan results for a single AWS service or a single resource type within a service.

### ISSUE THREAD

**Issue by BigDataDaddy** [iann0036/former2#260]
Hi, I recently did a full account scan of a big AWS account.   I see that some of my EC2 ASGs don't have all the instance associated with them since before the scan took place.  Is there any way I can just rescan a specific resource type, like ASGs for example, or a single AWS service to effectively re-sync my scan results with the account?   I really don't want to have to do a full account scan again because it takes so long. 

Thx.

**Comment by iann0036** [comment]
Hey @BigDataDaddy,

It's not immediately obvious but if you click the recycle-looking button just above the datatable, this will refresh all resources for a specific service (i.e. all EC2 instances, ASGs etc., but not S3 buckets for example).

<img width="1149" alt="Screen Shot 2022-08-01 at 8 53 14 pm" src="https://user-images.githubusercontent.com/4401744/182268893-15aba50f-75f1-45de-9a21-6d721d3b0c9c.png">

**Comment by BigDataDaddy** [comment]
HI @iann0036,
I'll give that a shot next time I run into it.

**Comment by BigDataDaddy** [comment]
I did some service level rescans this past week to pick up some newly created AWS resources.  The method described above worked flawlessly.  

Thanks~
