### ISSUE TITLE
Error exporting Kinesis and CloudFront from CLI

### ISSUE THREAD

**Issue by nishu** [iann0036/former2#265]
Hi, 

I am able to export the other resources seamlessly but face challenges with Kinesis (~40 data streams) and Cloudfront (~150 distributions)

For Kinesis log is not very helpful but it looks like some API limitations are being hit:
```
1660389120796: Kinesis.listStreams - {}
1660389123646: Kinesis.listStreams - {}
Too many requests for Kinesis.listStreams, sleeping for 3984ms
1660389255082: Kinesis.listStreams - {}
```

For CloudFront, it seems like the API requests for the same resource are being made repeatedly. 

Request any suggestions on how to circumvent this issue - 
Is there a way to make the log more verbose to debug both these issues? 
Are there any resources that should be excluded to make the fetch faster?

**Comment by iann0036** [comment]
Hi @nishu,

Thanks for raising!

For debugging in the CLI, `--debug` should show you some more detailed messaging (though will disrupt the progress bar be warned).

The "Too many requests" indicator shows that we're getting a backoff request from the API and the request should exponentially back off. If the ms value keeps increasing, there's likely a problem but if it eventually completes it's probably just a little slow.

There hasn't been extensive testing with large, paginated lists of resources, so there may be bugs unseen. Any further logs from using --debug would be helpful. The longest-to-run services are typically IAM followed by S3 in my experience.

**Comment by nishu** [comment]
This was solved after waiting for a few days and using the web browser version with the extension installed.
