### ISSUE TITLE
Glue Trigger missing Crawler/Job Actions

### ISSUE THREAD

**Issue by namman2** [iann0036/former2#266]
Hello,

I just started using Former2 for simplifying CF deployments and primarily just using it to simply AWS Glue workflow deployments with Triggers/Jobs/Crawlers.

The auto-generated template from both the UI and the CLI covers almost all of the use cases and it's very helpful, except for issue with missing "Actions" section in the AWS::Glue::Triggers component.

**Generated by Former2:**
![image](https://user-images.githubusercontent.com/14961628/184914066-420bcb69-ae64-454c-871f-3395411a821a.png)

**What the trigger looks like in the Console**
I was hoping the Job(s)/Crawler(s) at the start of the Trigger to show under Actions but it's missing.
![image](https://user-images.githubusercontent.com/14961628/184913379-37c5faa5-431e-443b-ac93-887faea32e57.png)

Is there a workaround or fix for this or Actions have to be manually added in the auto-generated CFT template? The "Predicates" variable populates fine, but was just having issues with the Actions not showing up on Glue Triggers from Former2.

Thank you in advance!

**Comment by iann0036** [comment]
Hi @namman2,

Thanks for raising!

That was indeed a bug during generation and should now be fixed. Let me know how it goes when you attempt now.

**Comment by namman2** [comment]
Hi @iann0036,

Thank you so much for your prompt response and fix for this! I tried it on the Chrome extension UI and it worked fine and returned the Actions tied to a Trigger.

Is there a possibility to have the CLI Former2 in NPM can also be updated with this fix? The CLI has been stable and easier for our use and would like to have this fix reflected there as well, it seems like the NPM version is the same after re-installing the package.

Thank you again!!

**Comment by iann0036** [comment]
Hey @namman2,

Thanks for confirming. I've bumped the CLI to 0.2.74 which should have those changes.

**Comment by namman2** [comment]
Thank you! Tested this on both CLI and GUI with Chrome extension and it works now.
