### ISSUE TITLE
VPC - Network ACL - Can't add

### ISSUE THREAD

**Issue by brodie11** [iann0036/former2#27]
Many of my network ACLs are defined as:

All Traffic - All - All - Source (some ip range).

On the Network ACL Entries tab, I see the NACL ids, but it shows undefined undefined in the CIDR block portion.  Even with the ones that have a specific protocol (UDP) and port (500), it does not show up.  This is for GovCloud West.

When I expand the details, the CIDR block does show up correctly which is odd.  I just can't add them to my template.

**Comment by iann0036** [comment]
Hi Brodie,

Thanks for raising this. I believe I found both the undefined issue, and the issue with it not adding to the template. This _should_ work now, but give it a shot and let me know.

**Comment by brodie11** [comment]
Yasssss!  That definitely works for both - I can see all the data and it's been added to my template!  You  have a seriously amazing tool here.  Keep up the great work!
