### ISSUE TITLE
RoboMaker ListFleets and ListRobots

### ISSUE THREAD

**Issue by bborup** [iann0036/former2#270]
Is "former2" trying to pull RoboMaker information using "ListFleets" and "ListRobots"?  

We've been contacted by AWS RoboMaker product management informing us that we have been using these two APIs but that they are deprecated.

We have no RoboMaker services in our accounts, so were wondering if this is where the hit is coming from.

Thanks.

**Comment by iann0036** [comment]
Hey @bborup,

Someone else raised something similar, where we were: https://github.com/iann0036/former2/issues/252

This should be fixed in the latest version though.
