### ISSUE TITLE
Former2 hanging on Chrome

### ISSUE THREAD

**Issue by wallwriting** [iann0036/former2#28]
I am trying to scan my Glue resources. Even after a half hour, the I still see the wait circle--the one that comes up before I'm allowed to select the resources to include in the output. I am able to do this for other services fine (I've done IAM and S3, for example).

**Comment by iann0036** [comment]
Hi,

Sorry to hear you're having trouble. I've made a slight change that may unblock the wait circle, but this usually means there's a bug with the response it's getting vs. the response it's expecting.

Could you let me know if you are unblocked now and if you see any errors in your browser console view? (sanitise anything sensitive before posting!) Also if you're missing any specific Glue resources you'd otherwise expect to show up.

**Comment by wallwriting** [comment]
![Screenshot 2019-11-12 at 6 17 35 PM](https://user-images.githubusercontent.com/14979521/68727285-cfe00180-0578-11ea-8d5d-3821cd3117a5.png)

Should I be doing anything to refresh the app? I restarted Chrome and tried again, and I still get the wait screen. I can see some of the correct resources behind the gray.

**Comment by iann0036** [comment]
Refresh the page should be good enough to refresh the app.

Could you attempt the same thing and then go to **View -> Developer -> Developer Tools** and see if there are any messages shown in the "Console" tab, particularly if they're highlighted red?

**Comment by wallwriting** [comment]
Nothing shows up on the console.

**Comment by wallwriting** [comment]
Oh, one other thing, since you had mentioned refreshing the app before, I'm not sure if this matters, but I wasn't able to refresh the page or even close the tab. It's locked up. I had to close Chrome altogether.

**Comment by iann0036** [comment]
Hmm. It's possible the error might be getting sent to the Chrome extension...if you are using it?

If so, can you navigate to chrome://extensions/ and click the "background page" link under Former2 Helper and check for any logs?

If that doesn't help, could you shoot me an e-mail directly to contact [at] ianmckay.com.au if you'd be willing to help me with some further debugging.

Thanks for your patience and help!

**Comment by wallwriting** [comment]
Huh, so I tried this on a third laptop, and it comes up fine now. I have no idea why it didn't work on the first 2. In any event, thanks for your time walking through all this. This is a great tool.
