### ISSUE TITLE
AWS::ElasticLoadBalancing::LoadBalancer swaps instanceport and instanceprotocol.

### ISSUE THREAD

**Issue by tmblue** [iann0036/former2#29]
Example:
"Type": "AWS::ElasticLoadBalancing::LoadBalancer",
            "Properties": {
                "LoadBalancerName": "",
                "Listeners": [
                    {
                        "InstancePort": "HTTP",
                        "InstanceProtocol": 80,
                        "LoadBalancerPort": 443,
                        "PolicyNames": [

**Comment by iann0036** [comment]
Thanks for the find!

Got that deployed for you now. Should be fine once the cache is dropped.
