### ISSUE TITLE
Error TypeError: obj.data.tags is undefined

### ISSUE THREAD

**Issue by marmig0404** [iann0036/former2#297]
When adding resources which have tags with no values, I receive this error on the web interface:
`Error TypeError: obj.data.tags is undefined`.
![image](https://user-images.githubusercontent.com/10036276/226736581-fda71a16-b25f-448e-bb11-804f64a01c51.png)

This is not a problem with some resources like Dynamo Tables, where it will generate a cloud formation template with a value for the tag as an empty string: `''`.
Other times, it is a problem, such as with a APIGatewayV2, it fails to add it to the cloud formation at all.

**Comment by marmig0404** [comment]
I've gone ahead and added a few different APIGWv2 resources to the list to generate, when adding any APIGWv2 resources from my account, I get the type error. 

[This gist](https://gist.github.com/marmig0404/d94c6c59ef69996cddcc2dc2fda0782b) shows the debug output and the cloud formation. In the debug output, it shows the resource type: `apigatewayv2.api`, but that resource doesn't appear in the cloud formation. 

I tried changing the tags to have a value of `true` but the tag manager on the AWS console only let me change the tags on eligible resources. I'm assuming it didn't affect the resources which are giving this issue, and it still persists.

**Comment by iann0036** [comment]
Hey @marmig0404,

Thanks for that information, super helpful.

I believe I've spotted and corrected the issue. Could you try again now and let me know how you go?

**Comment by marmig0404** [comment]
Looks to be working, thanks for the help!
