### ISSUE TITLE
Add option to skip loading cognito users

### ISSUE THREAD

**Issue by JustinBerger** [iann0036/former2#298]
Similar to the option to ignore irrelevant resources that skips log groups, if you have too many cognito users, it fails to load the user pool page (even though I'm not on the users tab yet)

Lots of the following lines in the logs.
Too many requests for CognitoIdentityServiceProvider.adminGetUser, sleeping for 500ms
Too many requests for CognitoIdentityServiceProvider.adminListGroupsForUser, sleeping for 7632ms

**Comment by iann0036** [comment]
Hey @JustinBerger,

Thanks for raising!

I agree with your suggestion. I've added Cognito users to the irrelevant resources group. You should be able to test that immediately. Let me know how it goes.
