### ISSUE TITLE
elbv2 listenerrules : default not an integer. Don't include it. It's in the listener already

### ISSUE THREAD

**Issue by tmblue** [iann0036/former2#30]
Priority: default, is not an integer and in fact it's 100% incorrect in terms of a listenerrule. The default is handled inside the listener and should not be created on output.
     
Listener:
        "elbv27da68c4": {
            "Type": "AWS::ElasticLoadBalancingV2::Listener",
            "Properties": {
                "LoadBalancerArn": {some ELB },
                "Port": 80,
                "Protocol": "HTTP",
                "DefaultActions": [
                    {
                        "Order": 1,
                        **"TargetGroupArn": {some target group},
                        "Type": "forward"**
                    }

Listenerrule below is redundant and in fact will fail, if attempted to use. Best to eliminate this from any and all outputs.

  "elbv2d009637": {
            "Type": "AWS::ElasticLoadBalancingV2::ListenerRule",
            "Properties": {
                "Priority": **"default"**,
                "ListenerArn": {some listener arn},
                "Actions": [
                    {
                        "Type": "forward",
                        "TargetGroupArn": {

**Comment by iann0036** [comment]
Just to confirm, non-default listener rules are still valid and are not defined anywhere in the listener?
