### ISSUE TITLE
Fails to load DynamoDB tables with CRC32 integrity check errors

### ISSUE THREAD

**Issue by lamontadams** [iann0036/former2#304]
Hi there,

I'm trying to scan an account in the EU (Ireland) region using Chromium and Firefox. I'm using IAM user credentials that have been given the `ReadOnlyAccess` permission policy. 

When former scans the account, I see repeated error toasts with the message "Error calling DynamoDB.describeTable CRC32 integrity check failed" and the DynamoDB tab becomes stuck in a loading animation -- though I see some tables in the listing. All I see in the browser console are "Too many requests for XXX, sleeping..." messages. 

This situation has survived a browser restart, uninstalling and reinstalling the browser add-in in both browsers. 

Any ideas?

**Comment by iann0036** [comment]
Hi @lamontadams,

I can't replicate this myself, but I found an option that's likely relevant. Could you try again now?

**Comment by lamontadams** [comment]
Going to close this because I don't think it's occurring any longer. Thanks.
