### ISSUE TITLE
AWS::CloudFront::Distribution CustomErrorResponse if ResponsePagePath and ResponseCode are null, don't include cloudformation output

### ISSUE THREAD

**Issue by tmblue** [iann0036/former2#31]
Example  

                   "CustomErrorResponses": [
                        {
                            "ErrorCode": 404,
                            "ResponsePagePath": "",
                            "ResponseCode": "",
                            "ErrorCachingMinTTL": 20

AWS will reject it, it will not accept null here and expects an integer, This one had nothing configured, so there needs to be some logic to dictate when it's included or not.

{/DistributionConfig/CustomErrorResponses/0/ResponseCode} does not match type {Integer}, Value of property {/DistributionConfig/CustomErrorResponses/1/ResponseCode} does not match type {Integer}, Value of property

**Comment by iann0036** [comment]
Should the entire object be excluded or is the following valid in your opinion?
```
"CustomErrorResponses": [
    {
        "ErrorCode": 404,
        "ErrorCachingMinTTL": 20
    }
]
```
