### ISSUE TITLE
Former2 doesn’t generate code for S3 Bucket when Intelligent-Tiering Archive is enabled and the configuration scope is “This configuration applies to all objects in the bucket”.

### ISSUE THREAD

**Issue by newyama** [iann0036/former2#316]
Former2 doesn’t generate code for S3 Bucket when Intelligent-Tiering Archive is enabled and the configuration scope is “This configuration applies to all objects in the bucket”.
When I try to generate code for S3 Bucket, Former2 says “TypeError: Cannot read properties of undefined (reading ‘Prefix’)”.
Probably, if the user selected “This configuration applies to all objects in the bucket” in the configuration of Intelligent-Tiering Archive, the parameter Prefix is hidden, but Former2 will try to read Prefix.
Please check it. Thank you.

**Comment by iann0036** [comment]
Hey @newyama,

Thanks for raising!

I've pushed a fix that should hopefully fix that issue. Could you try again now?

**Comment by newyama** [comment]
I have verified that it is fixed. Thank you for your response！
