### ISSUE TITLE
AWS::CloudFront::Distribution DistributionConfig setting  HttpVersion" HTTP2 != http2 cloudformation output

### ISSUE THREAD

**Issue by tmblue** [iann0036/former2#32]
"DistributionConfig": {
                    **"HttpVersion": "HTTP2",**
                    "IPV6Enabled": true

Value 'HTTP2' at 'distributionConfigWithTags.distributionConfig.httpVersion' failed to satisfy constraint: Member must satisfy enum value set: [http2, http1.1]

HttpVersion:
Type: String
Allowed Values: http1.1 | http2

Let me know if these are helpful, sometimes I am not sure what I should bubble up for you all to fix..

**Comment by iann0036** [comment]
Hi there,

Thanks for raising this. Looks like the docs were lying to me 😫

These issues are _very_ helpful as I can't test every property myself. I appreciate it and please continue!

In this case, looks like you found a docs bug (or an implementation bug).
