### ISSUE TITLE
I cannot get all record sets in Route53

### ISSUE THREAD

**Issue by tsukimiya** [iann0036/former2#325]
If there are more than 101 records in one HostedZone, it seems that only 100 records can be retrieved.
Is there a way around this behavior?

Thanks for providing a great product.

**Comment by iann0036** [comment]
Hey @tsukimiya,

Thanks for raising!

I've added a change that should hopefully fix the 100 limit. Could you try again and let me know how you go?

**Comment by iann0036** [comment]
Thanks @tsukimiya,

That's interesting. Would you happen to have records with non-simple routing policies within your zone? I've made an adjustment to better support those. Let me know if that's still having the same issue.

**Comment by tsukimiya** [comment]
@iann0036 
I have checked and the problem has not been resolved.
With only a simple routing policy in the hostedzone, it contains the following.
* NS and SOA records created as soon as hostedzone is created
* A Record
* CNAME Record
* TXT Record
* NS record for delegation of subdomains

**Comment by iann0036** [comment]
Sorry for the persistent problem @tsukimiya,

Could I confirm if you are using the browser version, at former2.com?

**Comment by iann0036** [comment]
Apologies for the issues @tsukimiya,

I may have a better fix for you now. Could you try again?

**Comment by tsukimiya** [comment]
@iann0036 
Great!
I confirm that the problem has been resolved.
Thank you very much.

![image](https://github.com/iann0036/former2/assets/71832/c110ea69-5e74-4f2a-94c7-11b167b27bfb)
