### ISSUE TITLE
UAE (me-central-1) region not present

### ISSUE THREAD

**Issue by aaditunni-unityinfotech** [iann0036/former2#332]
The Middle East region UAE (me-central-1) is not present in the list of regions. All the resources that I want to import to terraform are in this region.

**Comment by iann0036** [comment]
Hi @aaditunni-unityinfotech,

Thanks for raising! I've made that change for you now which should be effective in a couple minutes.

**Comment by aaditunni-unityinfotech** [comment]
Thanks @iann0036. Appreciate it! Also, I just noticed that there is a mistake in the index.html for the UAE region. It is supposed to be me-central-1.

**Comment by iann0036** [comment]
Whoops! Good catch.

Fix on the way :)

**Comment by aaditunni-unityinfotech** [comment]
@iann0036 No worries :)
