### ISSUE TITLE
RDS scan error

### ISSUE THREAD

**Issue by jsonthepython** [iann0036/former2#334]
I have this error toast during the scan:

> Error calling DocDB.describeDBClusters
Unrecognized engine name: docdb

I have only 3 databases: 3 RDS PostgreSQL

I don't find those in left pane menu `Database/RDS`

However, it seems that they are generated correctly when I generate all resources using the `Add All Resources` button.

I'm beginning with IaC so I can't check output validity.

Thanks

**Comment by iann0036** [comment]
Hi @jsonthepython,

Thanks for raising!

Looks like this issue only occurs in certain newer regions, which is strange. It looks like the filter isn't at all needed, so I've removed it to hopefully ensure this error doesn't reoccur. Let me know how you go.

**Comment by iann0036** [comment]
Hi @jsonthepython,

I did some further digging. Turns out this filter is required but the reason it errors is due to regional availability (the service responds, just not helpfully). I've chosen to simply ignore these errors instead.

**Comment by jsonthepython** [comment]
Hello @iann0036,

Yes, the error is gone! My region is Stockholm.


> I don't find those in left pane menu Database/RDS

I was looking in the wrong tab, everything's fine :)
