### ISSUE TITLE
Kendra Datasources and Faqs result in an error during scan

### ISSUE THREAD

**Issue by kevinmalloy-untitled** [iann0036/former2#342]
![image](https://github.com/iann0036/former2/assets/97060064/bfd64b0e-aa37-4025-a9ed-5720da0648bc)

Both list datasources and list faqs require an IndexId, from the looks of it the function in /js/services/kendra.js is not passing any parameters.

**Comment by iann0036** [comment]
Hi @kevinmalloy-untitled,

Thanks for raising!

I've updated the function you identified to include the index as parameters. Give that another try now and let me know how you go.

**Comment by kevinmalloy-untitled** [comment]
Looks good to me, thank you for the quick fix!
