### ISSUE TITLE
Try to scan account getting the following error

### ISSUE THREAD

**Issue by rdamji27** [iann0036/former2#35]
Error calling EC2.searchTransitGatewayRoutes
Missing required key 'Filters' in params

I am trying to scan the entire account and this error shows up, I am unsure what to add in the parameters section to avoid this error.

Thanks

Rd

**Comment by iann0036** [comment]
Hi there,

Thanks so much for raising this. Looks like filters are required in the API when looking up transit gateway routes (and I missed this previously).

The error should be fixed up now but I can't test it effectively. Could you give this another try when you're free?

**Comment by rdamji27** [comment]
Thanks You resolved
Rahim
    On Wednesday, November 27, 2019, 01:40:49 AM EST, Ian Mckay <notifications@github.com> wrote:  
 
 
Hi there,

Thanks so much for raising this. Looks like filters are required in the API when looking up transit gateway routes (and I missed this previously).

The error should be fixed up now but I can't test it effectively. Could you give this another try when you're free?
