### ISSUE TITLE
ec2 image builder module doesn't pull code for components to export as CDK/CFT

### ISSUE THREAD

**Issue by M66605** [iann0036/former2#357]
When the platform enumerates EC2 Image Builder components it doesn't bring along the AWSTOE code in the component in order to transform the discovery into a CDK/CFT output.

**Comment by iann0036** [comment]
Hi @johnowens00,

I've added a minor fix to include the `Data` field for the EC2 Image Builder components. I hope this matches what you are referring to.

Give it another go now.
