### ISSUE TITLE
using former2 programmatically

### ISSUE THREAD

**Issue by 3p3r** [iann0036/former2#42]
Hi!

Thanks for this fantastic tool. I have a question. I need to use Former2 programmatically. What's the best way to accomplish this beside using something like puppeteer?

Thanks!

**Comment by anzi-codepipeline** [comment]
Hi Sepehr,

Unfortunately, there's no good way to do this currently. May I know your use case?

**Comment by iann0036** [comment]
Hi Sepehr,

Unfortunately, there's no good way to do this currently. May I know your use case?

**Comment by 3p3r** [comment]
Absolutely. I wanted to package this up in a Lambda and have it run and generate a nightly snapshot of my entire environment.

I could use puppeteer for that, but I figured I'd double check with you first.

**Comment by iann0036** [comment]
Thanks for the feedback!

I've built something experimental over at [npm.js](https://www.npmjs.com/package/former2). Did you want to give it a try and let me know if you have any feedback / feature requests?

**Comment by 3p3r** [comment]
Perfect! Thanks for the quick support :)
I will use this and get back to you with feedback.

**Comment by iann0036** [comment]
Thanks for your help with those items @3p3r!

Those have been merged in as v0.2.5.

**Comment by 3p3r** [comment]
Awesome! Thank you. I will keep sending you PRs as I use it more and more in the following weeks.
