### ISSUE TITLE
Add support for AWS profiles in CLI

### ISSUE THREAD

**Issue by tabascoterrier** [iann0036/former2#46]
Former2 was already incredibly useful, thanks for making it, and a CLI makes it even better.

Would you consider adding support for [named profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) like the to ease use against multiple accounts? e.g.

```bash
former2 --profile development ...
former2 --profile production ...
```

**Comment by iann0036** [comment]
Hi there,

Thanks for the feedback and for raising!

I've added in `--profile` and `--region` support in version 0.2.9. Please let me know if you see any problems.

**Comment by tabascoterrier** [comment]
Outstanding, thank you!  I've taken it for a quick spin and everything looks great.
