### ISSUE TITLE
ElasticBeanstalk CNAME is not a valid URL

### ISSUE THREAD

**Issue by natetallman** [iann0036/former2#48]
In looking at the data that is returned for ElasticBeanstalk environments, the CNAME value is a hostname, not a valid url to be passed to `new URL()`. When generating output for Beanstalk environments, I got an error `Uncaught TypeError: Failed to construct 'URL': Invalid URL`. I was able to get around the issue temporarily by prepending the CNAME value with `https://`, but I don't know if that is the optimal solution.

https://github.com/iann0036/former2/blob/2a894248b540d3bd8d0446792679c5df864da3dc/js/mappings.js#L4027-L4028

**Comment by iann0036** [comment]
Hi Nate,

Thanks soo much for raising!

I concur with your suggestion to prepend `https://` and have pushed this up. Let me know if this fixes your issue and that you get the expected result (I'm not overly familiar with EB's URL scheme, so please correct me if it's wrong!).

**Comment by enm10k** [comment]
I'm at the latest master and seeing a related issue.

```
$ git rev-parse HEAD
6c6ba22a9d9f9cc294cf393cdede2fa1ec394532
```

In my environment, an actual CNAME is like `aaa-bbb-ccc-ddd` but I get `ddd`.
I'm going to check the code later.

**Comment by iann0036** [comment]
Thanks for the pull request.
