### ISSUE TITLE
Errors reading from S3

### ISSUE THREAD

**Issue by dmeadows** [iann0036/former2#5]
Getting errors in chrome when trying to load s3: 

Uncaught (in promise) null
datatables.js:203 Skipping S3.listBuckets NetworkingError
datatables.js:5550 Uncaught (in promise) null
chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71 Uncaught (in promise) Error: Extension context invalidated.
    at chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71
    at Object.makeRequest (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71)
    at d (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71)
    at Object.sendRequest (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71)
    at Object.requestFunction (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71)
    at Object.callRepository (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71)
    at chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71
    at new Promise (<anonymous>)
    at Object.t.callBackgroundRepository (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71)
    at e.setFrameReady (chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/onloadwff.js:71)

**Comment by iann0036** [comment]
This error I see usually is related to either not having the helper extension installed or a firewall blocking it. Would it be possible to try it with both Chrome and Firefox, both with the helper installed to help us narrow down the cause?

**Comment by iann0036** [comment]
Closing, inactive.

**Comment by shqear-mawdoo3** [comment]
I have the same issue here
```
Skipping S3.listBuckets NetworkingError  s3.js:275

updateDatatableStorageS3 | @ | s3.js:275
-- | -- | --
  | async function (async) |   |  
  | updateDatatableStorageS3 | @ | s3.js:136
  | dispatch | @ | jquery-3.2.1.min.js:3
  | q.handle | @ | jquery-3.2.1.min.js:3
  | trigger | @ | jquery-3.2.1.min.js:4
  | (anonymous) | @ | jquery-3.2.1.min.js:4
  | each | @ | jquery-3.2.1.min.js:2
  | each | @ | jquery-3.2.1.min.js:2
  | trigger | @ | jquery-3.2.1.min.js:4
  | trigger | @ | bootstrap-table.js:5378
  | refresh | @ | bootstrap-table.js:6430
  | (anonymous) | @ | bootstrap-table.js:4211
  | dispatch | @ | jquery-3.2.1.min.js:3
  | q.handle | @ | jquery-3.2.1.min.js:3
```

And something similar in ApiGateway either : 
```
Skipping ApiGatewayV2.getApis NetworkingError

updateDatatableNetworkingAndContentDeliveryAPIGateway | @ | apigateway.js:1951
-- | -- | --
  | async function (async) |   |  
  | updateDatatableNetworkingAndContentDeliveryAPIGateway | @ | apigateway.js:1346
  | dispatch | @ | jquery-3.2.1.min.js:3
  | q.handle | @ | jquery-3.2.1.min.js:3
  | trigger | @ | jquery-3.2.1.min.js:4
  | (anonymous) | @ | jquery-3.2.1.min.js:4
  | each | @ | jquery-3.2.1.min.js:2
  | each | @ | jquery-3.2.1.min.js:2
  | trigger | @ | jquery-3.2.1.min.js:4
  | trigger | @ | bootstrap-table.js:5378
  | refresh | @ | bootstrap-table.js:6430
  | (anonymous) | @ | bootstrap-table.js:4211
  | dispatch | @ | jquery-3.2.1.min.js:3
  | q.handle | @ | jquery-3.2.1.min.js:3
```

**Comment by shqear-mawdoo3** [comment]
I went to Extenstion icon -> Manage Extenstion -> Enabled all urls below and it worked : 
![image](https://user-images.githubusercontent.com/59925620/83684748-3483ac00-a5f0-11ea-9f56-b49573675ba8.png)

**Comment by iann0036** [comment]
Hey @shqear-mawdoo3,

Thanks for reporting back. Were these enabled URLs something you specifically disabled at some point? I believe they should be enabled when the extension is installed.

**Comment by shqear-mawdoo3** [comment]
@iann0036 I'm not sure, but I don't think so, I always allow permissions by defaults for such tools
