### ISSUE TITLE
Error from generated AWS::EC2::Subnet - missing Ipv6CidrBlock

### ISSUE THREAD

**Issue by rainabba** [iann0036/former2#51]
**`AssignIpv6AddressOnCreation: false`** was included, but **`Ipv6CidrBlock`** was not.

Per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-ipv6cidrblock:
> If you specify AssignIpv6AddressOnCreation, you must also specify Ipv6CidrBlock.

Here's a quick-n-dirty suggestion (not confident enough of your logic to do a PR at this time or I would).

https://raw.githubusercontent.com/iann0036/former2/master/js/mappings.js#3119

```javascript
                    if ( obj.data.AssignIpv6AddressOnCreation ) {
                        reqParams.cfn['AssignIpv6AddressOnCreation'] = obj.data.AssignIpv6AddressOnCreation;
                        reqParams.tf['assign_ipv6_address_on_creation'] = obj.data.AssignIpv6AddressOnCreation;

                        reqParams.cfn['Ipv6CidrBlock'] = obj.data.Ipv6CidrBlock;
                        reqParams.tf['ipv6-cidr-block'] = obj.data.Ipv6CidrBlock;

                        /* TODO:
                        Tags:
                            - Resource Tag
                        */
                    }
```

**Comment by iann0036** [comment]
Cheers @rainabba, I agree.

The [data structure](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeSubnets-property) for that seems to be in an array, but I believe the referenced commit will do the job.

Let me know if that works for you.

**Comment by rainabba** [comment]
I may be misunderstanding your mention of an array, but these are only strings so I don't think there's any issue there. I think that change should be good. I don't see any test suite setup (checked to see if I could test and do a PR) for the project so I can't say more confidently.

Also, I'd love to see that mappings.js broken down into sub-files. Looking for someone to help out here and there (mostly out of selfish interest :grin:)? 

Not saying I'd do much, but I continue to find this tool very helpful and little stuff like this would be no big deal if you're open to direct PR's (not Google 8-step process :stuck_out_tongue:).

**Comment by iann0036** [comment]
Yeah, unfortunately test suites would be beyond my capacity. I'm positive not even AWS have comprehensive test suites for CloudFormation (I'm trying to build something over [here](https://github.com/iann0036/cfn-leastprivilege/tree/master/tests)).

I've been meaning to split this project into sub-files (per service namespace) for some time. I'll probably do that shortly.

Happy for you to help out - honestly the most helpful thing right now is getting bug reports and hearing how people are using it or where they're getting stuck. Feel free to PR, I've had a couple already.
