### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by reidca** [iann0036/former2#56]
I love this tool, it is something that AWS should have built in to the console and I am extremely grateful for it.

Unfortunately I am having a lot of performance issues using it.

I would estimate I have only managed to complete a full scan a couple of times, the other times the Chrome process hangs with an unresponsive dialog and the progress counter stops. The last time it was at item 34/102. 

On occasion it comes back to life and very slowly moves forward until it stops again.
It rarely completes before I have to close Chrome completely.

I have also tried Firefox but have had similar results.

Is there anything I can do to further diagnose or improve the performance?

Thanks

![image](https://user-images.githubusercontent.com/7325010/74345795-8933ba80-4da6-11ea-96ea-e7b3b4c06d1e.png)

**Comment by iann0036** [comment]
Hey @reidca,

Sorry to hear you're having performance issues in this area. The underlying reason is that all services are spawning promises simultaneously on the main browser thread, which kills UI performance. The correct solution here is to shift the work onto a web worker, or throttle the concurrent promises or both.

I'll look into doing this soon, however it'll likely take a few days to figure out.

**Comment by iann0036** [comment]
Hi @reidca,

I've made a performance improvement to limit the load during account scanning. Could you give this a try and report on your browser performance?

**Comment by reidca** [comment]
I have tried the entire account scan a couple of times this morning but on both occasions it has crashed without making any progress.

The button is still showing 0/102

I had to forcibly close the Chrome tab

Just a thought but I think the "Action" of scan entire account should not be in the "Settings".
It just doesn't feel like the right location for an activity. Changing settings should be a passive activity.

**Comment by iann0036** [comment]
Hi @reidca,

Sorry you're still having issues with the crashes. What are the rough specs of the computer you're running it on?

Could you try executing the following line of code in a DevTools console just before you scan:

```MAX_DT_SCANS = 2;```

Note it will slow down the scan considerably, it was about a 3 minutes run for me. If that works, try increase the number to see the speed/performance balance (the original value is 10).

I also agree the scan button is in the wrong location currently. I'll have to think of a better place for it.

**Comment by iann0036** [comment]
Actually, scratch that entirely.

I think I found a major CPU slowdown that would be causing the performance issues. Could you try again now with no changes?

**Comment by reidca** [comment]
Wow, massive improvement. Completed the scan in about 1 minute!

There were a few pop up errors about permissions missing for some services. Not sure why as the role has the managed read only policy attached to it but I think in my case it's safe to ignore these.

Thank you so much.

**Comment by iann0036** [comment]
Awesome!

I'm aware some of the managed policy issues. Often I need slightly more than it has or the managed policy falls behind the service releases (by months in some circumstances).

Safe to ignore if you don't mind missing one or two resource types.

Thanks for your help in testing 🙇
