### ISSUE TITLE
Cannot fetch ConfigurationTemplates of ElasticBeanstalk

### ISSUE THREAD

**Issue by enm10k** [iann0036/former2#62]
I tried to scan an ElasticBeanstalk stack, but I cannot fetch ConfigurationTemplates.
Is there any existing issue or do I miss something?
As far as I see, no errors in Chrome browser.

**Comment by iann0036** [comment]
Hi @enm10k,

Thanks for reporting this. Can you elaborate on exactly what you're seeing? I'm assuming you're saying the Configuration Templates are not showing in the table to be added to the stack.

Configuration Templates are called on top of found stacks so could you confirm the stack you expect appears in its list?

**Comment by enm10k** [comment]
Thanks for your quick response!

> ... Can you elaborate on exactly what you're seeing? I'm assuming you're saying the Configuration Templates are not showing in the table to be added to the stack.

Yes, that's right.

> Configuration Templates are called on top of found stacks so could you confirm the stack you expect appears in its list?

I can see my resources on `Applications, Application Versions, Environments` sections, but not on  `Configuration Templates`.

Btw, I wrote a script to get what I needed using troposphere.
https://gist.github.com/enm10k/bdccf91a2ef1724f333dffdff64ba8ba

**Comment by iann0036** [comment]
Hey @enm10k,

Thanks for confirming.

I have a feeling the call may be silently requiring both application and environment name to the call (even though the docs say different). I've updated the table to perform this.

Could you give it a try again and let me know?

**Comment by enm10k** [comment]
> Could you give it a try again and let me know?

Thanks! It works fine.
Now I can see Configuration Templates.
