### ISSUE TITLE
Error generating template for autoscaling group scheduled action

### ISSUE THREAD

**Issue by nigrogianluca** [iann0036/former2#63]
Hi 

I'm getting an error trying to generate a template for ASG scheduled actions

I'm using Firefox Developer Edition with the firefor-helper customized for my private server in AWS where I host former2

console.trace() TypeError: "obj.data.StartTime.toISOString is not a function"
    <anonymous> http://staging.aws.gsped.it/former2/js/services/autoscaling.js:167
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2280
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2278
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2266
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:662
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:661
    <anonymous> http://staging.aws.gsped.it/former2/js/app.js:655
    jQuery 8
    <anonymous> http://staging.aws.gsped.it/former2/js/app.js:654
    jQuery 13
mappings.js:3:40
    f2trace http://staging.aws.gsped.it/former2/js/mappings.js:3
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2291
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2278
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2266
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:662
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:661
    <anonima> http://staging.aws.gsped.it/former2/js/app.js:655
    jQuery 8
    <anonima> http://staging.aws.gsped.it/former2/js/app.js:654
    jQuery 13
{"id":"arn:aws:autoscaling:eu-west-1:XXXXXXXX:scheduledUpdateGroupAction:1de36dae-ac72-4074-b685-257395858d9d:autoScalingGroupName/Gsped Labeling Legacy:scheduledActionName/accende mattina in settimana","type":"autoscaling.scheduledaction","data":{"AutoScalingGroupName":"Gsped Labeling Legacy","ScheduledActionName":"accende mattina in settimana","ScheduledActionARN":"arn:aws:autoscaling:eu-west-1:XXXXXXXX:scheduledUpdateGroupAction:1de36dae-ac72-4074-b685-257395858d9d:autoScalingGroupName/Gsped Labeling Legacy:scheduledActionName/accende mattina in settimana","Time":"2020-02-24T05:00:00.000Z","StartTime":"2020-02-24T05:00:00.000Z","Recurrence":"0 5 * * MON-FRI","MinSize":3,"MaxSize":9,"DesiredCapacity":3},"region":"eu-west-1"}

If I try the same action on standard firefox (with CORS error on scanning) I get

console.trace() TypeError: "obj.data.EndTime is undefined"
    <anonymous> http://staging.aws.gsped.it/former2/js/services/autoscaling.js:169
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2280
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2278
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2266
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:662
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:661
    <anonymous> http://staging.aws.gsped.it/former2/js/app.js:655
    jQuery 2
mappings.js:3:40
    f2trace http://staging.aws.gsped.it/former2/js/mappings.js:3
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2291
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2278
    performF2Mappings http://staging.aws.gsped.it/former2/js/mappings.js:2266
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:662
    regenerateOutputs http://staging.aws.gsped.it/former2/js/app.js:661
    <anonima> http://staging.aws.gsped.it/former2/js/app.js:655
    jQuery 2

**Comment by iann0036** [comment]
Hi @nigrogianluca,

Thanks for raising!

Looks like I had an unneeded conversion in that particular mapping. The linked commit should fix that issue (or pull from master).

Let me know if that helps.

**Comment by nigrogianluca** [comment]
Hi Ian

thanks for looking into that, I tested and now works fine!!

I'll let you know if I find other problems.

BTW kudos for former2, it's extremely useful, keep up the good work.
