### ISSUE TITLE
Error in parameter replacement

### ISSUE THREAD

**Issue by cairnswm** [iann0036/former2#68]
Error in parameter replacement

I have this section in my template
            Runtime: "python3.6"
            Timeout: **3**
            TracingConfig: 
                Mode: "PassThrough"

I added the following parameter
  SF: 3MV

when I regenerate: The above section is changed to
            Runtime: "python3.6"
            Timeout: **!Ref 3MV**
            TracingConfig: 
                Mode: "PassThrough"

Should not have found the number 3 as matching 3MV
Should have replaced it with !Ref SF and not with the value of SF

In other areas the SF replacement worked correctly

**Comment by iann0036** [comment]
Hey @cairnswm,

Thanks for picking up on this!

The mentioned fix should solve this issue.
