### ISSUE TITLE
Parameter to AWS inconsistencies

### ISSUE THREAD

**Issue by cairnswm** [iann0036/former2#69]
In Former 2 you can create parameters like SF_ID. This replaces into the template correctly including creating the parameter for replacement when executed.

However an underscore is an invalid character in a cloud formation template. When converting to a template the underscore needs to be removed in both the parameter list and where it is used for a !Ref or !Sub

**Comment by iann0036** [comment]
Hey @cairnswm,

I've added an input mask to the parameter name, so it should disallow you from entering invalid parameter names so hopefully this should suffice.

**Comment by cairnswm** [comment]
I dont think that would help as I need to replace those variables, its just when written into the template that the problem is encountered.

If have a Config value
SF_ID = XYZ

I want XYZ to be part of the parameter list so that I can change it on next run.

**Comment by iann0036** [comment]
I don't think I understand the issue. You'll still be able to do replacements with parameters, this change simply means that the parameter names will be validated as alphanumeric as [per the documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#parameters-section-structure-requirements).

So you could still do SFID = XYZ in your case and change that as you please.

**Comment by cairnswm** [comment]
I'll test it :)



(Flying to Switzerland in a few hours - so only much later)

**Comment by cairnswm** [comment]
Great news - it worked perfectly :)

Thanks
