### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by jodybro** [iann0036/former2#7]
Adding aws api keys to any external website is a no no in my opinion.
Running this locally on docker should be the recommended way forward.

Tested with `nginx:1.15` and it worked like a charm.

`FROM nginx:1.15`
`COPY . /usr/share/nginx/html`

The above is all that's really needed. Port 80 is exposed by default in the container.
Build with `docker build -t former2_local:1.0 .`
Run the container with `docker run --name former2 -p $host_port:80 -d former2_local:1.0`

**Comment by iann0036** [comment]
Cheers!

Added per your spec.
