### ISSUE TITLE
Wrong attribute name for S3 server-side encryption by default

### ISSUE THREAD

**Issue by fruffin** [iann0036/former2#70]
When exporting an S3 bucket with server-side encryption enabled by default, Former2 generates a server-side encryption rule with the attribute `ApplyServerSideEncryptionByDefault` where it should be `ServerSideEncryptionByDefault`

**Comment by iann0036** [comment]
Hey @fruffin,

Thanks heaps for raising!

The referenced commit should fix that issue, but let me know if that's not the case.
