### ISSUE TITLE
Site helper + EC2 Hosted Former2 - Hanging on S3 resources

### ISSUE THREAD

**Issue by xtrearer** [iann0036/former2#76]
Hi,

I hosted Former2 on a t2.micro EC2 instance that is only accessible by my local machine (various work related reasons).

I have the helper installed on Chrome. I have been able to scan and export all of my resources, except of course S3. On that one, it just hangs. 

Am I missing something? Is this kind of setup supported?

P.S. thank you for making this!!

**Comment by iann0036** [comment]
Hey @xtrearer,

How long ago did you test this roughly? I [fixed](https://github.com/iann0036/former2/commit/ef76b715384f53b4115a20e1cef4c7ceca43a642) a possibly related bug about 20 minutes ago if it's hanging when you attempt to add resources to the stack.

**Comment by xtrearer** [comment]
Thank you for the quick response!

Yes, I actually saw that you fixed it. I re-downloaded the package again, redeployed, but I'm still getting the issue. 

I've attached a screenshot showing the s3 failures. As for logs...

/#section-storage-s3:1 Access to XMLHttpRequest at 'https://s3.eu-west-1.amazonaws.com/' from origin 'http://ec2-34-249-3-122.eu-west-1.compute.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
aws-sdk-2.632.0.min.js:6 GET https://s3.eu-west-1.amazonaws.com/ net::ERR_FAILED

I see that the helper is allowing "https://*.amazonaws.com/*". I did not setup my EC2 host with SSL, so my URL is http://*... The Helper is also complaining it cannot connect when on the EC2 hosted tab, but it is happy when I switch to the AWS Console tab. I will try to rehost the EC2 with SSL. Will let you know.

![image](https://user-images.githubusercontent.com/64196731/80086592-3a4e9200-855a-11ea-9ca9-e08212d33bc8.png)

**Comment by iann0036** [comment]
Hey @xtrearer,

Thanks for the clarification. I believe the issue is that the helper extension isn't actually effective for the host you're using. You may need to download the helper files and change the  (https://github.com/iann0036/former2-helper) files [here](https://github.com/iann0036/former2-helper/blob/master/chrome/bg.js#L3) and [here](https://github.com/iann0036/former2-helper/blob/master/chrome/manifest.json#L25), then load the extension directly.

I don't think you'll need to add SSL to your site.

**Comment by xtrearer** [comment]
Ok,

I've edited the manifest, which has allowed the Helper to now run on the EC2 URL.

I however do not know how to edit the line you indicated on the bg.js. This line:

        if (["127.0.0.1", "localhost", "former2.com", "www.former2.com"].includes(new URL(sender.url).hostname)) {

Should I be adding something to the [ ] list, or hardcode the sender.url to the EC2 URL?

Disclaimer, I am a pure Google/Stackoverflow developer... haha. So be gentle.

**Comment by iann0036** [comment]
Yep, just need to add to the list, i.e.
```
    if (["127.0.0.1", "localhost", "former2.com", "www.former2.com", "your.hostname"].includes(new URL(sender.url).hostname)) {
```

Once that's done, you can load it in by removing the existing Former2 Helper extension and using the "Load unpacked" button in chrome://extensions

**Comment by xtrearer** [comment]
Thanks for all the help so far. Really appreciate it!

I've updated with the below:

["127.0.0.1", "localhost", "former2.com", "www.former2.com", "ec2-aaa.bbb.ccc.ddd.eu-west-1.compute.amazonaws.com"]

Reloaded the helper. But it is still not working.

/#section-storage-s3:1 Access to XMLHttpRequest at 'https://s3.eu-west-1.amazonaws.com/' from origin 'http://ec2-34-249-3-122.eu-west-1.compute.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
aws-sdk-2.632.0.min.js:6 GET https://s3.eu-west-1.amazonaws.com/ net::ERR_FAILED

How can I check the header on the request?

**Comment by iann0036** [comment]
Oh, my apologies. I completely forgot about one extra step!

Grab your new extension ID from the chrome://extensions/ area and change the hosted js/app.js file at line 1343 to the new ID.

**Comment by xtrearer** [comment]
I got the new ID and updated js/apps.js as you requested. 

Reloaded. On resources like EC2, where the scan worked, it now reports "Error calling EC2.describeInstances. You are not authorized to perform this operation.".

S3 is still failing with the old error message. 

Seems updating apps.js made it worse?

**Comment by iann0036** [comment]
Weird.

Could you try going to the credentials screen, removing your credentials out and click Next, then go back and re-add them? Might not have picked up the change.

**Comment by xtrearer** [comment]
Good news! I'm an idiot... with all the resetting etc, forgot to switch back to the proper AWS Region.

So with apps.js updating, the normal ones are working again.

Bad news... S3 still complains:

Access to XMLHttpRequest at 'https://s3.eu-west-1.amazonaws.com/' from origin 'http://ec2-34-249-3-122.eu-west-1.compute.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by iann0036** [comment]
Oof.

I might some time to fully replicate this myself (and document the process!). Can I get back to you in a day or so?

**Comment by xtrearer** [comment]
For sure! You have helped me so much already. Thank you again!

Just for context again:

1. Downloaded your Former2 zip (twice, with the latest code).
2. Created an EC2 instance using the Amazon Linux AMI 2018.03.0.20200318.2 x86_64 HVM gp2.
3. Followed this AWS guide: [https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Tutorials.WebServerDB.CreateWebServer.html](url)
4. Dumped the zip contents into /var/www/html on the EC2.
5. Followed the Former2 Helper steps described here (Download code, modify and Load).

**Comment by iann0036** [comment]
Hey @xtrearer,

I've added some detailed instructions [here](https://github.com/iann0036/former2/blob/master/HOSTING.md) which is roughly what we went through. Could you take a look at the document, specifically noting the formats of the URLs in various places (i.e. with http:// & /* or without) ?

**Comment by xtrearer** [comment]
Will do!

**Comment by xtrearer** [comment]
You are an absolute legend! 

And I am an idiot. The issue was on the manifest.json. 

I only updated the "permissions" section, and forgot to update the "externally_connectable". I can now scan the S3 resources.

Thank you so much again for your effort in this. I am blown away...

**Comment by iann0036** [comment]
Great to hear! Thanks for helping me make those docs 😄
