### ISSUE TITLE
Elasticache(Redis) - NotificationConfiguration and CacheNodes Fields are not available.

### ISSUE THREAD

**Issue by dheeraj-cn** [iann0036/former2#80]
Hey,
First of all, really good product.

I am trying to use former2 to generate Cf script for Redis clusters. It fails because [NotificationConfiguration](https://github.com/iann0036/former2/blob/9775b4201f4ee1e892148f502631c05717cf842a/js/services/elasticache.js#L438) and [CacheNodes](https://github.com/iann0036/former2/blob/9775b4201f4ee1e892148f502631c05717cf842a/js/services/elasticache.js#L452) are not available. I think we just need to add a condition to check if these fields exist.
Can you please have a look?
Thanks for your time.

**Comment by iann0036** [comment]
Sorry for the extreme delay. I didn't notice this issue coming through. Fixed in mainline.
