### ISSUE TITLE
404 Not found: Nginx Error for Diagram output

### ISSUE THREAD

**Issue by rams3sh** [iann0036/former2#81]
I am experimenting with former2. 

I have loaded the credentials and have been getting all the other outputs properly. However, the diagram is not being displayed

![image](https://user-images.githubusercontent.com/5143597/83950085-ab65b280-a845-11ea-9ac1-f48bb0f77d2b.png)

**Comment by iann0036** [comment]
Hey @rams3sh,

Thanks for raising this.

It looks like the Git submodule for the diagramming portion didn't execute for some reason. Could you let me know how you cloned/downloaded this repo?

You should be able to execute the following from the root of the repo in the meantime to see if it fixes your issue:

```
cd lib
rm drawio
git clone https://github.com/jgraph/drawio
```

Let me know if that works for you.

**Comment by rams3sh** [comment]
Hey @iann0036 

Thanks, your suggestion worked. Apparently I cloned the repo using :-
```
git clone https://github.com/iann0036/former2
```

It didnt clone the refferred repository in `lib/drawio` . The drawio folder was empty. My bad.

Instead I should have done a recursive clone using :-
```
git clone --recursive https://github.com/iann0036/former2
```
Closing the ticket , since the issue is resolved.
