### ISSUE TITLE
Large number of resources leads to stuck output compilation step (CLI)

### ISSUE THREAD

**Issue by Vardominator** [iann0036/former2#86]
When trying to capture an AWS environment with a large number of deployed services, the process hangs here and never finishes (either Terraform or CloudFormation):
```
████████████████████████████████████████  100% (108/108 services completed)
```
In this case `cli_resources.length` is `13693`. It seems like the culprit is [this line](https://github.com/Vardominator/former2/blob/810d0c8fb821f6033a29c4867c16972667b94579/cli/main.js#L158).

I have to significantly filter down the search such that the output file is no larger than 12,000 lines (~340KB).

I am testing on a `c5.4xlarge` running Ubuntu 18.04, using the following commands:
```
UV_THREADPOOL_SIZE=32
/bin/node --stack-size=16384 /former2/cli/main.js generate --region us-east-1 --output-terraform /tmp/backup.tf
```

The strange thing is I don't run into this issue with my Mac.

**Comment by iann0036** [comment]
Hi @Vardominator,

Sorry for the delayed response. This is, to be honest, an immense data size that I haven't catered for. I suspect this may be due to something like log groups consuming the majority of resources.

Is it possible to get a count by internal type?

**Comment by Vardominator** [comment]
I have added an `--exclude-services` argument to exclude entire sections (e.g. cloudwatch), and additionally filtered down significantly for the process not to hang. Nonetheless, here is an example with only cloudwatch excluded:
```
node main.js generate --region us-east-1 --exclude-services cloudwatch --output-terraform /tmp/backup.tf
```

The f2.type counts:
```
  { f2type: 'ec2.networkinterface', count: 2431 },
  { f2type: 'ec2.volumeattachment', count: 145 },
  { f2type: 'ec2.volume', count: 145 },
  { f2type: 'ec2.instance', count: 132 },
  { f2type: 'route53.record', count: 126 },
  { f2type: 'ec2.networkinterfaceattachment', count: 123 },
  { f2type: 'ec2.securitygroup', count: 103 }, 
  { f2type: 'lambda.version', count: 99 },
  { f2type: 'autoscaling.launchconfiguration', count: 91 },
  { f2type: 'iam.role', count: 73 },
  { f2type: 'iam.user', count: 65 },
  { f2type: 'iam.accesskey', count: 64 },
  { f2type: 's3.bucket', count: 63 },
  { f2type: 'ec2.route', count: 62 },
  { f2type: 'iam.policy', count: 56 },
  { f2type: 'ec2.subnetnetworkaclassociation', count: 55 },
  { f2type: 'ec2.subnet', count: 55 },
  { f2type: 'iam.managedpolicy', count: 48 },
  { f2type: 'ec2.subnetroutetableassociation', count: 40 },
  { f2type: 'lambda.function', count: 29 },
  { f2type: 'iam.instanceprofile', count: 28 },
  { f2type: 'sqs.queuepolicy', count: 26 },
  { f2type: 'sqs.queue', count: 26 },
  { f2type: 'ec2.routetable', count: 22 },
  { f2type: 'documentdb.instance', count: 21 },
  { f2type: 'rds.instance', count: 21 },
  { f2type: 'neptune.instance', count: 21 },
  { f2type: 'iam.servicelinkedrole', count: 20 },
  { f2type: 'ec2.networkaclentry', count: 18 },
  { f2type: 'kms.key', count: 16 },
  { f2type: 'ec2.elasticip', count: 14 },
  { f2type: 'eventbridge.rule', count: 14 },
  { f2type: 'acm.certificate', count: 14 },
  { f2type: 'elasticache.parametergroup', count: 13 },
  { f2type: 'ecr.repository', count: 13 },
  { f2type: 'elbv2.targetgroup', count: 11 },
  { f2type: 'elbv2.loadbalancerlistenerrule', count: 10 },
  { f2type: 'elbv2.loadbalancerlistener', count: 10 },
  { f2type: 'elbv2.loadbalancer', count: 10 },
  { f2type: 'neptune.cluster', count: 10 },
  { f2type: 'documentdb.cluster', count: 10 },
  { f2type: 'rds.cluster', count: 10 },
  { f2type: 'ec2.networkacl', count: 9 },
...
```

The above fails to complete on an Ubuntu 18.04 based c5.4xlarge.

**Comment by iann0036** [comment]
Thanks @Vardominator,

I've gone ahead and added your `--exclude-services cloudwatch` suggestion into main and made some other improvements that should hopefully speed things up somewhat (I'd still recommend including the CloudWatch exclusion).

I've also added a log when running with the `--debug` option that will tell you what resource type is internally being worked on when generating the output. This might give us some further clues if there is a specific type that is slowing down or hanging. I personally have around 1000 resources and it took around 15 seconds from the time the service scan finished.

Let me know how you go with the latest (0.2.47).

**Comment by Vardominator** [comment]
Wow! It actually finishes and is significantly faster.
I'm glad you also added `--exclude-services`.
Thanks a lot!

**Comment by iann0036** [comment]
Great to hear, and thanks for your help.

Feel free to re-raise if you spot any further significant slowdowns.
