### ISSUE TITLE
Missing policies after Role creation

### ISSUE THREAD

**Issue by jvargh** [iann0036/former2#88]
Hi- Cloudformation template does not capture assigned IAM policies during Role creation. However Boto and CLI output does.

**Comment by iann0036** [comment]
Hi @jvargh,

Could you elaborate? Are you selecting some found IAM policies on the former2.com website and after generation they do not appear?

**Comment by jvargh** [comment]
Hi Ian- You're right on selection of role on former2 site and after generation does not appear. Boto3 shows them fine but not Cfn. Let know if this helps. Similar issue with Console Recorder also

Boto3
[cid:c9a5eaac-2ab6-42ad-9cfc-43bd90fa4b39]

Cloudformation
[cid:1eb3db9e-4c0d-4908-bf8f-936391c4b478]


________________________________

**Comment by iann0036** [comment]
Thanks @jvargh,

Just confirming, was it a role or policy that is not shown? Note that policies are detailed as a seperate tab from roles in Former2 (there are two ways to represent their relationship in CloudFormation; I had to pick one).

If that doesn't solve the issue, could you confirm whether reference to the policy or role is shown in the **Raw Output (Debug)** Outputs section?

**Comment by jvargh** [comment]
Awkward. Seems to be there now in Cfn after retest in former2, after selecting role and generate. Can this be fixed in Console Recorder by any chance?
Also in former2 site don’t see Boto3 as an output option, would help greatly if there..

Former2
[cid:image003.jpg@01D6715A.A4335070]
ConsoleRec
[cid:image004.png@01D6715A.A4335070]

**Comment by iann0036** [comment]
Cheers, I'll look into that for Console Recorder.

As for the lack of Boto3 here, it's mostly due to Former2 being optimised for Infrastructure-as-Code. A boto3 equivalent would assume a bunch of create and modify calls, but it's hard to design for an unknown state - which is different in Console Recorder as I can see the full read/delete etc. requests. Soo, very long term roadmap item 👍 .
