### ISSUE TITLE
Route53 Private Hosted Zone missing associated VPC

### ISSUE THREAD

**Issue by reidca** [iann0036/former2#90]
I have created a private hosted zone with an associated VPC but Former2 does not generate this relationship when creating the template.

The property https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone-hostedzonevpcs.html is not added to the template.

**Comment by reidca** [comment]
Thank you for doing this so quickly. I can confirm, that this is now showing in the template generation.

I did notice a couple of JS errors appearing, not sure whether these are important or not:

```
mappings.js:3 ReferenceError: ipv6Range is not defined
    at ec2.js:2706
    at Array.forEach (<anonymous>)
    at ec2.js:2703
    at Array.forEach (<anonymous>)
    at ec2.js:2665
    at mappings.js:4377
    at Array.forEach (<anonymous>)
    at mappings.js:4375
    at Array.forEach (<anonymous>)
    at performF2Mappings (mappings.js:4361)
f2trace @ mappings.js:3
mappings.js:3 TypeError: Cannot read property 'type' of undefined
    at ecs.js:986
    at Array.forEach (<anonymous>)
    at ecs.js:824
    at mappings.js:4377
    at Array.forEach (<anonymous>)
    at mappings.js:4375
    at Array.forEach (<anonymous>)
    at performF2Mappings (mappings.js:4361)
    at checkRelatedResources (app.js:183)
    at addSelectedRowsToTemplate (app.js:436)
f2trace @ mappings.js:3
mappings.js:1810 No request ID found for wafregional
getResourceName @ mappings.js:1810
```

**Comment by iann0036** [comment]
Thanks for those also!

Fixed the first two. The "No request ID found" error can be safely ignored, I believe it's a tiny edge case that's been catered for.

**Comment by reidca** [comment]
Perfect support! Not sure how you manage to work so quickly but it's appreciated.
